import sys
sys.path.append('../Character')
import json
import sys
from character import Character
from script import *
from scriptGraph import ScriptGraph
from characterDefinitions import CHARACTER_FOLDER

# Auto-generated file
# Name: Bilingual_Lego
# Character: female
activity_name = 'Spanish group activity'
class Bilingual_Lego(ScriptGraph) :
    def __init__(self):
        super().__init__()

    def init_graph(self):


        self.graph.add_node('start', type=['character'])
        self.graph.add_edge('start', 'Node_2', label='start_2')
        self.graph.add_node('Node_2', type=['speak', 'move'], text='Hello friends! I`m Gigi the robot!', motors='wave_hello')
        self.graph.add_edge('Node_2', 'Node_3', label='Node_2_3')
        self.graph.add_node('Node_3', type=['audio'], audio='../Assets/audio/laugh.wav')
        self.graph.add_edge('Node_3', 'Node_4', label='Node_3_4')
        self.graph.add_node('Node_4', type=['speak'], text='I love building with LEGO and playing with my friends.')
        self.graph.add_edge('Node_4', 'Node_5', label='Node_4_5')
        self.graph.add_node('Node_5', type=['speak', 'face'], text='Would you like to play with me? #¿Quieren jugar conmigo? #', face=basic_sequences['look_up'])
        self.graph.add_edge('Node_5', 'Node_6', label='Node_5_6')
        self.graph.add_node('Node_6', type=['hear'], words='["yes", "si", "[unk]"]')
        self.graph.add_node('Node_7', type=['speak'], text='Great!')
        self.graph.add_edge('Node_6', 'Node_7', label='yes')
        self.graph.add_edge('Node_7', 'Node_8', label='Node_7_8')
        self.graph.add_node('Node_8', type=['speak'], text='#¡Excelente!#')
        self.graph.add_edge('Node_6', 'Node_8', label='si')
        self.graph.add_edge('Node_8', 'Node_9', label='Node_8_9')
        self.graph.add_node('Node_9', type=['speak'], text='How do you say "hello" in Spanish?', pause={'after': 3})
        self.graph.add_edge('Node_9', 'Node_10', label='Node_9_10')
        self.graph.add_node('Node_10', type=['hear'], words='["hola", "[unk]"]')
        self.graph.add_node('Node_11', type=['speak'], text='That`s right. # ¡hola! # Let`s all say it together: #¡hola!#')
        self.graph.add_edge('Node_10', 'Node_11', label='hola')
        self.graph.add_edge('Node_11', 'Node_12', label='Node_11_12')
        self.graph.add_node('Node_12', type=[], pause={'after': 3})
        self.graph.add_edge('Node_12', 'Node_13', label='Node_12_13')
        self.graph.add_node('Node_13', type=['speak', 'move'], text='If you want to play, raise your hands! # ¡Levanten las manos! #', motors='arms_up', pause={'after': 2})
        self.graph.add_edge('Node_13', 'Node_14', label='Node_13_14')
        self.graph.add_node('Node_14', type=['speak'], text='High. Higher. This is great!')
        self.graph.add_edge('Node_14', 'Node_15', label='Node_14_15')
        self.graph.add_node('Node_15', type=['speak', 'move'], text='I`m so happy you want to play with me.', motors='arms_down')
        self.graph.add_edge('Node_15', 'Node_16', label='Node_15_16')
        self.graph.add_node('Node_16', type=['speak', 'move'], text='But before we start, let`s say hello to each other in English and Spanish.', motors='look_from_side_to_side', pause={'after': 5})
        self.graph.add_edge('Node_16', 'Node_17', label='Node_16_17')
        self.graph.add_node('Node_17', type=['speak', 'show', 'move'], text='Can you see? You have a bin with LEGO blocks and figures on the table.', image='../Assets/Bilingual_Lego/lego.png', motors='arms_down')
        self.graph.add_edge('Node_17', 'Node_18', label='Node_17_18')
        self.graph.add_node('Node_18', type=['speak'], text='Can you find a LEGO figure that you like?')
        self.graph.add_edge('Node_18', 'Node_19', label='Node_18_19')
        self.graph.add_node('Node_19', type=['speak'], text='Everyone can choose one LEGO figure and decorate it. # Elijan una figura LEGO y decórenla. #')
        self.graph.add_edge('Node_19', 'Node_20', label='Node_19_20')
        self.graph.add_node('Node_20', type=['speak'], text='When you are done, raise the black and white card in front of you. # Cuando terminen, levanten la tarjeta en blanco y negro. #')
        self.graph.add_edge('Node_20', 'Node_21', label='Node_20_21')
        self.graph.add_node('Node_21', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_22', type=['speak'], text='I see you are having fun. Let me know when you are done by raising the card.')
        self.graph.add_edge('Node_21', 'Node_22', label='no')
        self.graph.add_edge('Node_22', 'Node_21', label='Node_22_21')
        self.graph.add_node('Node_23', type=['speak'], text='Did you pick a boy or a girl? What kind of hair do they have? Curly? Straight? What color is their shirt?')
        self.graph.add_edge('Node_21', 'Node_23', label='yes')
        self.graph.add_edge('Node_23', 'Node_24', label='Node_23_24')
        self.graph.add_node('Node_24', type=['speak', 'move'], text='Show your friends your figure and tell them what you picked.', motors='look_from_side_to_side', pause={'after': 10})
        self.graph.add_edge('Node_24', 'Node_25', label='Node_24_25')
        self.graph.add_node('Node_25', type=['speak'], text='Now we`re ready to start!# ¡Vamos a empezar!#')
        self.graph.add_edge('Node_25', 'Node_26', label='Node_25_26')
        self.graph.add_node('Node_26', type=['speak'], text='Today we`re going to build a Ferris wheel. Or in Spanish, we say #la noria.# Do you know what a Ferris wheel is? Tell your friends. # Hoy vamos a construir la noria. ¿Saben qué es? Cuéntenle a sus amigos.#', pause={'after': 10})
        self.graph.add_edge('Node_26', 'Node_27', label='Node_26_27')
        self.graph.add_node('Node_27', type=['speak', 'audio'], text='Yes! A Ferris wheel is a big wheel that spins. Or in Spanish, #gira#, round and round. You can find Ferris wheels in carnivals! I love them! # ¡Sí! Es una rueda grande que gira y gira. ¡Las puedes encontrar en ferias! ¡Me encantan!#', audio='../Assets/audio/laugh.wav')
        self.graph.add_edge('Node_27', 'Node_28', label='Node_27_28')
        self.graph.add_node('Node_28', type=['speak'], text='Have you ever been on a Ferris wheel? Tell your friends. # ¿Alguna vez han subido a una noria? Cuéntenle a sus amigos.#', pause={'after': 10})
        self.graph.add_edge('Node_28', 'Node_29', label='Node_28_29')
        self.graph.add_node('Node_29', type=['speak'], text='Today we will build a big Ferris wheel for our LEGO friends together! # ¡Hoy construiremos una gran noria para nuestros amigos LEGO juntos! #')
        self.graph.add_edge('Node_29', 'Node_30', label='Node_29_30')
        self.graph.add_node('Node_30', type=['speak', 'face', 'move'], text='Look at the bin at the center of your table! It has all the pieces. Or in Spanish, #las piezas.# We need to build a Ferris wheel. So let`s get started! # Miren la caja en el centro de la mesa. ¡Tiene todas las piezas que necesitamos! #', face=basic_sequences['look_down'], motors='arms_down')
        self.graph.add_edge('Node_30', 'Node_31', label='Node_30_31')
        self.graph.add_node('Node_31', type=['speak'], text='Are you ready? # ¿Están listos? #')
        self.graph.add_edge('Node_31', 'Node_32', label='Node_31_32')
        self.graph.add_node('Node_32', type=['hear'], words='["yes", "si", "[unk]"]')
        self.graph.add_node('Node_33', type=['speak'], text='Great! # ¡Muy bien!')
        self.graph.add_edge('Node_32', 'Node_33', label='yes')
        self.graph.add_edge('Node_33', 'Node_34', label='Node_33_34')
        self.graph.add_node('Node_34', type=['speak'], text='#¡Excelente!#')
        self.graph.add_edge('Node_32', 'Node_34', label='si')
        self.graph.add_edge('Node_34', 'Node_35', label='Node_34_35')
        self.graph.add_node('Node_35', type=['speak'], text='Today we`re going to build a Ferris wheel. or as we say in Spanish, *la noria*.')
        self.graph.add_edge('Node_35', 'Node_36', label='Node_35_36')
        self.graph.add_node('Node_36', type=['speak'], text='Do you know what a Ferris wheel is? Tell your friends.', pause={'after': 10})
        self.graph.add_edge('Node_36', 'Node_37', label='Node_36_37')
        self.graph.add_node('Node_37', type=['speak'], text='Yes! A Ferris wheel is a big wheel that spins. *gira*, round and round. You can find Ferris wheels in carnivals! I love them!')
        self.graph.add_edge('Node_37', 'Node_38', label='Node_37_38')
        self.graph.add_node('Node_38', type=['audio'], audio='../Assets/audio/laugh.wav')
        self.graph.add_edge('Node_38', 'Node_39', label='Node_38_39')
        self.graph.add_node('Node_39', type=['speak'], text='Have you ever been on a Ferris wheel? Tell your friends.', pause={'after': 10})
        self.graph.add_edge('Node_39', 'Node_40', label='Node_39_40')
        self.graph.add_node('Node_40', type=['speak'], text='Today we will build a big Ferris wheel for our LEGO friends together! # Hoy construiremos una gran noria para nuestros amigos de LEGO.  #')
        self.graph.add_edge('Node_40', 'Node_41', label='Node_40_41')
        self.graph.add_node('Node_41', type=['speak'], text='Look at the bin at the center of your table! It has all the pieces. *las piezas*. we need to build our Ferris wheel.')
        self.graph.add_edge('Node_41', 'Node_42', label='Node_41_42')
        self.graph.add_node('Node_42', type=['speak', 'face', 'move'], text='So let`s get started! # ¡Vamos a empezar! #', face=basic_sequences['look_down'], motors='arms_down')
        self.graph.add_edge('Node_42', 'Node_43', label='Node_42_43')
        self.graph.add_node('Node_43', type=['speak'], text='Are you ready? # ¿Están listos?  #')
        self.graph.add_edge('Node_43', 'Node_44', label='Node_43_44')
        self.graph.add_node('Node_44', type=['hear'], words='["yes", "si", "[unk]"]')
        self.graph.add_node('Node_45', type=['speak'], text='Great!')
        self.graph.add_edge('Node_44', 'Node_45', label='yes')
        self.graph.add_edge('Node_45', 'Node_46', label='Node_45_46')
        self.graph.add_node('Node_46', type=['speak'], text='#¡Excelente!#')
        self.graph.add_edge('Node_44', 'Node_46', label='si')
        self.graph.add_edge('Node_46', 'Node_47', label='Node_46_47')
        self.graph.add_node('Node_47', type=['speak'], text='Now connect the motor to the gray LEGO plate. the base.')
        self.graph.add_edge('Node_47', 'Node_48', label='Node_47_48')
        self.graph.add_node('Node_48', type=['speak'], text='How do we say to connect in Spanish? Can anyone tell me? # ¿Cómo se dice# to connect #en español? ¿Alguien lo sabe?#')
        self.graph.add_edge('Node_48', 'Node_49', label='Node_48_49')
        self.graph.add_node('Node_49', type=['hear'], words='["conectar", "[unk]"]')
        self.graph.add_node('Node_50', type=['speak'], text='That`s right! #¡conectar! Conecten el motor a la placa gris de LEGO la base.')
        self.graph.add_edge('Node_49', 'Node_50', label='conectar')
        self.graph.add_edge('Node_50', 'Node_51', label='Node_50_51')
        self.graph.add_node('Node_51', type=['speak'], text='One person holds the base while the other clicks the motor in. #Uno sostiene la base mientras el otro coloca el motor.')
        self.graph.add_edge('Node_51', 'Node_52', label='Node_51_52')
        self.graph.add_node('Node_52', type=['speak'], text='Raise your card when you are ready. # Levanten la tarjeta cuando terminen. #')
        self.graph.add_edge('Node_52', 'Node_53', label='Node_52_53')
        self.graph.add_node('Node_53', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_54', type=['speak'], text='Not quite done? I will wait. # ¿Todavía no? Aquí espero.#')
        self.graph.add_edge('Node_53', 'Node_54', label='no')
        self.graph.add_edge('Node_54', 'Node_53', label='Node_54_53')
        self.graph.add_node('Node_55', type=['speak'], text='Excellent teamwork! # ¡Buen trabajo en equipo!#')
        self.graph.add_edge('Node_53', 'Node_55', label='yes')
        self.graph.add_edge('Node_55', 'Node_56', label='Node_55_56')
        self.graph.add_node('Node_56', type=['speak'], text='now let`s build a tower! In Spanish we say: #un torre#.')
        self.graph.add_edge('Node_56', 'Node_57', label='Node_56_57')
        self.graph.add_node('Node_57', type=['speak'], text='this tower is 3 blocks high!')
        self.graph.add_edge('Node_57', 'Node_58', label='Node_57_58')
        self.graph.add_node('Node_58', type=['speak'], text='Who can remind me how we count to three in Spanish?', pause={'after': 5})
        self.graph.add_edge('Node_58', 'Node_59', label='Node_58_59')
        self.graph.add_node('Node_59', type=['speak'], text='Thank you for teaching us. #uno, dos, tres.#')
        self.graph.add_edge('Node_59', 'Node_60', label='Node_59_60')
        self.graph.add_node('Node_60', type=['speak', 'move'], text='Let`s show what a tower looks like with our hands! Reach up tall like a tower, #a torre.!#', motors='arms_up')
        self.graph.add_edge('Node_60', 'Node_61', label='Node_60_61')
        self.graph.add_node('Node_61', type=['speak'], text='Now, stack three bricks to build a tower.')
        self.graph.add_edge('Node_61', 'Node_62', label='Node_61_62')
        self.graph.add_node('Node_62', type=['speak'], text='How do you say “tower” in your language? # ¿Cómo se dice “tower” en tu idioma?  #')
        self.graph.add_edge('Node_62', 'Node_63', label='Node_62_63')
        self.graph.add_node('Node_63', type=['speak'], text='Can you teach your friends? # ¿Quieres enseñarle a tus amigos?#', pause={'after': 5})
        self.graph.add_edge('Node_63', 'Node_64', label='Node_63_64')
        self.graph.add_node('Node_64', type=['speak'], text='One child can stack the blocks while another counts. Then switch!')
        self.graph.add_edge('Node_64', 'Node_65', label='Node_64_65')
        self.graph.add_node('Node_65', type=['speak'], text='When your tower is done, raise your card. # Cuando terminen su torre, levanten su tarjeta. #')
        self.graph.add_edge('Node_65', 'Node_66', label='Node_65_66')
        self.graph.add_node('Node_66', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_67', type=['speak'], text='Still building? Take your time.')
        self.graph.add_edge('Node_66', 'Node_67', label='no')
        self.graph.add_edge('Node_67', 'Node_66', label='Node_67_66')
        self.graph.add_node('Node_68', type=['speak'], text='Great tower! You worked together so well! # ¡Gran torre! ¡Trabajaron muy bien juntos!#')
        self.graph.add_edge('Node_66', 'Node_68', label='yes')
        self.graph.add_edge('Node_68', 'Node_69', label='Node_68_69')
        self.graph.add_node('Node_69', type=['speak', 'image'], text='Now, Put the tower next to the motor.')
        self.graph.add_edge('Node_69', 'Node_70', label='Node_69_70')
        self.graph.add_node('Node_70', type=['speak'], text='One friend holds the base, one friend  pushes.')
        self.graph.add_edge('Node_70', 'Node_71', label='Node_70_71')
        self.graph.add_node('Node_71', type=['speak', 'find'], text='Raise your card when you are done.', what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_72', type=['speak'], text='I will wait while you finish.')
        self.graph.add_edge('Node_71', 'Node_72', label='no')
        self.graph.add_edge('Node_72', 'Node_71', label='Node_72_71')
        self.graph.add_node('Node_73', type=['speak'], text='First tower. ready to roll!')
        self.graph.add_edge('Node_71', 'Node_73', label='yes')
        self.graph.add_edge('Node_73', 'Node_74', label='Node_73_74')
        self.graph.add_node('Node_74', type=['speak'], text='Build another tower, just like the first.')
        self.graph.add_edge('Node_74', 'Node_75', label='Node_74_75')
        self.graph.add_node('Node_75', type=['speak'], text='Remember to switch roles! #¡Recuerden cambiar de rol!#')
        self.graph.add_edge('Node_75', 'Node_76', label='Node_75_76')
        self.graph.add_node('Node_76', type=['speak'], text='When the second tower is standing next to the first one,, raise your card.')
        self.graph.add_edge('Node_76', 'Node_77', label='Node_76_77')
        self.graph.add_node('Node_77', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_78', type=['speak'], text='Not quite done? That`s okay.')
        self.graph.add_edge('Node_77', 'Node_78', label='no')
        self.graph.add_edge('Node_78', 'Node_77', label='Node_78_77')
        self.graph.add_node('Node_79', type=['speak'], text='Now we have two towers! # ¡dos torres!#')
        self.graph.add_edge('Node_77', 'Node_79', label='yes')
        self.graph.add_edge('Node_79', 'Node_80', label='Node_79_80')
        self.graph.add_node('Node_80', type=['speak'], text='Who remembers how we say spin in Spanish?')
        self.graph.add_edge('Node_80', 'Node_81', label='Node_80_81')
        self.graph.add_node('Node_81', type=[], pause={'after': 3})
        self.graph.add_edge('Node_81', 'Node_82', label='Node_81_82')
        self.graph.add_node('Node_82', type=['hear'], words='["girar", "[unk]"]')
        self.graph.add_node('Node_83', type=['speak'], text='That`s right. #girar!#')
        self.graph.add_edge('Node_82', 'Node_83', label='girar')
        self.graph.add_edge('Node_83', 'Node_84', label='Node_83_84')
        self.graph.add_node('Node_84', type=['speak', 'move'], text='Can you show me with your hands how something spins? # ¿Pueden mostrar con las manos cómo gira algo?  #', motors='circle_with_hands')
        self.graph.add_edge('Node_84', 'Node_85', label='Node_84_85')
        self.graph.add_node('Node_85', type=['speak'], text='Find the long black axle. # Busquen el eje negro.  #')
        self.graph.add_edge('Node_85', 'Node_86', label='Node_85_86')
        self.graph.add_node('Node_86', type=['speak'], text='Push it through both towers. One friend can hold, another one can push. #Uno sostiene, otro empuja.  #')
        self.graph.add_edge('Node_86', 'Node_87', label='Node_86_87')
        self.graph.add_node('Node_87', type=['speak'], text='Ready to spin? Try it,  then raise your card! # ¿Listos para girar? #')
        self.graph.add_edge('Node_87', 'Node_88', label='Node_87_88')
        self.graph.add_node('Node_88', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_89', type=['speak'], text='Keep going! # ¡Sigan así!#')
        self.graph.add_edge('Node_88', 'Node_89', label='no')
        self.graph.add_edge('Node_89', 'Node_88', label='Node_89_88')
        self.graph.add_node('Node_90', type=['speak'], text='Great axle work! #eje completo!#')
        self.graph.add_edge('Node_88', 'Node_90', label='yes')
        self.graph.add_edge('Node_90', 'Node_91', label='Node_90_91')
        self.graph.add_node('Node_91', type=['speak'], text='Find the green pieces to make an X. #forma de X#')
        self.graph.add_edge('Node_91', 'Node_92', label='Node_91_92')
        self.graph.add_node('Node_92', type=['speak'], text='One holds the wheel, the other clips them in.')
        self.graph.add_edge('Node_92', 'Node_93', label='Node_92_93')
        self.graph.add_node('Node_93', type=['speak'], text='When it`s ready, raise your card.')
        self.graph.add_edge('Node_93', 'Node_94', label='Node_93_94')
        self.graph.add_node('Node_94', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_95', type=['speak'], text='Still snapping pieces? That`s okay.')
        self.graph.add_edge('Node_94', 'Node_95', label='no')
        self.graph.add_edge('Node_95', 'Node_94', label='Node_95_94')
        self.graph.add_node('Node_96', type=['speak'], text='Awesome! Wheel arms are ready!')
        self.graph.add_edge('Node_94', 'Node_96', label='yes')
        self.graph.add_edge('Node_96', 'Node_97', label='Node_96_97')
        self.graph.add_node('Node_97', type=['speak'], text='Slide the wheel. #rueda.# onto the axle. #eje#')
        self.graph.add_edge('Node_97', 'Node_98', label='Node_97_98')
        self.graph.add_node('Node_98', type=['speak'], text='Take turns.  One holds, one slides.', pause={'after': 3})
        self.graph.add_edge('Node_98', 'Node_99', label='Node_98_99')
        self.graph.add_node('Node_99', type=['speak'], text='If it spins, raise your card!')
        self.graph.add_edge('Node_99', 'Node_100', label='Node_99_100')
        self.graph.add_node('Node_100', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_101', type=['speak'], text='Try again! I will wait.')
        self.graph.add_edge('Node_100', 'Node_101', label='no')
        self.graph.add_edge('Node_101', 'Node_100', label='Node_101_100')
        self.graph.add_node('Node_102', type=['speak'], text='Woohoo! The wheel is spinning! #¡Está girando!#')
        self.graph.add_edge('Node_100', 'Node_102', label='yes')
        self.graph.add_edge('Node_102', 'Node_103', label='Node_102_103')
        self.graph.add_node('Node_103', type=['speak'], text='How do we say seat in Spanish? # ¿Cómo se dice “seat”?  #', pause={'after': 3})
        self.graph.add_edge('Node_103', 'Node_104', label='Node_103_104')
        self.graph.add_node('Node_104', type=['hear'], words='["asiento", "[unk]"]')
        self.graph.add_node('Node_105', type=['speak'], text='That`s right. #asiento!#')
        self.graph.add_edge('Node_104', 'Node_105', label='asiento')
        self.graph.add_edge('Node_105', 'Node_106', label='Node_105_106')
        self.graph.add_node('Node_106', type=['speak'], text='Do you know another way to say it?')
        self.graph.add_edge('Node_106', 'Node_107', label='Node_106_107')
        self.graph.add_node('Node_107', type=['speak'], text='How do you say seat in your language?')
        self.graph.add_edge('Node_107', 'Node_108', label='Node_107_108')
        self.graph.add_node('Node_108', type=['speak'], text='Can you tell your friends?', pause={'after': 5})
        self.graph.add_edge('Node_108', 'Node_109', label='Node_108_109')
        self.graph.add_node('Node_109', type=['speak'], text='Use red and yellow bricks to build four small seats.')
        self.graph.add_edge('Node_109', 'Node_110', label='Node_109_110')
        self.graph.add_node('Node_110', type=['speak'], text='When they`re ready, raise your card.')
        self.graph.add_edge('Node_110', 'Node_111', label='Node_110_111')
        self.graph.add_node('Node_111', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_112', type=['speak'], text='Almost done? I will wait. # ¿Casi listos? Aquí espero. #')
        self.graph.add_edge('Node_111', 'Node_112', label='no')
        self.graph.add_edge('Node_112', 'Node_111', label='Node_112_111')
        self.graph.add_node('Node_113', type=['speak'], text='Look at those seats, #asientos.# Amazing work!')
        self.graph.add_edge('Node_111', 'Node_113', label='yes')
        self.graph.add_edge('Node_113', 'Node_114', label='Node_113_114')
        self.graph.add_node('Node_114', type=['speak'], text='Now, let`s connect the seats, #asientos.# Onto the ends of the green arms.')
        self.graph.add_edge('Node_114', 'Node_115', label='Node_114_115')
        self.graph.add_node('Node_115', type=['speak'], text='Take turns. One at a time. # Uno por uno. #')
        self.graph.add_edge('Node_115', 'Node_116', label='Node_115_116')
        self.graph.add_node('Node_116', type=['speak'], text='When they`re all on, raise your card.')
        self.graph.add_edge('Node_116', 'Node_117', label='Node_116_117')
        self.graph.add_node('Node_117', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_118', type=['speak'], text='Still working? I will wait! # ¿Todavía trabajando? Los espero.#')
        self.graph.add_edge('Node_117', 'Node_118', label='no')
        self.graph.add_edge('Node_118', 'Node_117', label='Node_118_117')
        self.graph.add_node('Node_119', type=['speak'], text='That looks amazing! You are almost finished and you are working together so nicely!')
        self.graph.add_edge('Node_117', 'Node_119', label='yes')
        self.graph.add_edge('Node_119', 'Node_120', label='Node_119_120')
        self.graph.add_node('Node_120', type=['speak'], text='Let`s double-check: Are your towers strong? #fuertes?# Is the wheel. #rueda.# connected?')
        self.graph.add_edge('Node_120', 'Node_121', label='Node_120_121')
        self.graph.add_node('Node_121', type=['speak'], text='One friend checks while the other spins. # Uno revisa mientras el otro gira.  #')
        self.graph.add_edge('Node_121', 'Node_122', label='Node_121_122')
        self.graph.add_node('Node_122', type=['speak'], text='When it looks ready, raise your card. # Si todo se ve bien, levanten su tarjeta.  #')
        self.graph.add_edge('Node_122', 'Node_123', label='Node_122_123')
        self.graph.add_node('Node_123', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_124', type=['speak'], text='Still checking? That`s smart. I will wait here.')
        self.graph.add_edge('Node_123', 'Node_124', label='no')
        self.graph.add_edge('Node_124', 'Node_123', label='Node_124_123')
        self.graph.add_node('Node_125', type=['speak'], text='Ready to test! You`ve helped each other every step of the way. # ¡Listos para probar! Se han ayudado durante todo el camino.#')
        self.graph.add_edge('Node_123', 'Node_125', label='yes')
        self.graph.add_edge('Node_125', 'Node_126', label='Node_125_126')
        self.graph.add_node('Node_126', type=['speak'], text='Spin your Ferris Wheel. #noria# Gently with your finger. What happens?', pause={'after': 5})
        self.graph.add_edge('Node_126', 'Node_127', label='Node_126_127')
        self.graph.add_node('Node_127', type=['speak'], text='Raise your card if it spins smoothly! #Si gira bien, levanten su tarjeta.  #')
        self.graph.add_edge('Node_127', 'Node_128', label='Node_127_128')
        self.graph.add_node('Node_128', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_129', type=['speak'], text='Try spinning again. I will wait for your signal. # Intenten girarla otra vez. Yo los espero. #')
        self.graph.add_edge('Node_128', 'Node_129', label='no')
        self.graph.add_edge('Node_129', 'Node_128', label='Node_129_128')
        self.graph.add_node('Node_130', type=['speak'], text='You did it! Our Ferris Wheel is standing tall and spinning around! You built it together.  High five your friend and give a big smile!')
        self.graph.add_edge('Node_128', 'Node_130', label='yes')
        self.graph.add_edge('Node_130', 'Node_131', label='Node_130_131')
        self.graph.add_node('Node_131', type=['move', 'speak'], motors='clap', text='Lets hear a big cheer!')
        self.graph.add_edge('Node_131', 'Node_132', label='Node_131_132')


if __name__ == "__main__":
    sg = Bilingual_Lego()
    sg.init_graph()

    fuzzy = Character(child=False, gender='female', activity='Bilingual_Lego', languages=['en', 'es'])
    script = Script(graph=sg, character=fuzzy)
    script.generateAllSpeech()
    script.check_assets()

