import sys
sys.path.append('../Character')
import json
import sys
import argparse
from character import Character
from script import *
from scriptGraph import ScriptGraph
import shutil
from characterDefinitions import CHARACTER_FOLDER

# Auto-generated file
# Name: Bilingual_Lego
# Character: female
activity_name = 'Bilingual_Lego'
class Bilingual_Lego(ScriptGraph) :
    def __init__(self):
        super().__init__()

    def init_graph(self):


        self.graph.add_node('start', type=['character'])
        self.graph.add_edge('start', 'Node_2', label='start_2')
        self.graph.add_node('Node_2', type=['speak', 'move'], text='Hello friends! I`m Gigi the robot!', motors='wave_hello')
        self.graph.add_edge('Node_2', 'Node_3', label='Node_2_3')
        self.graph.add_node('Node_3', type=['speak', 'move'], text='I love building with LEGO and playing with my friends.', motors='open_arms', pause={'after': 1})
        self.graph.add_edge('Node_3', 'Node_4', label='Node_3_4')
        self.graph.add_node('Node_4', type=['speak'], text='I also love learning new languages!')
        self.graph.add_edge('Node_4', 'Node_5', label='Node_4_5')
        self.graph.add_node('Node_5', type=['find'], what='face', timeout=10)
        self.graph.add_node('Node_6', type=['speak'], text='What languages do you speak?', pause={'after': 10})
        self.graph.add_edge('Node_5', 'Node_6', label='no')
        self.graph.add_edge('Node_6', 'Node_8', label='Node_6_8')
        self.graph.add_node('Node_7', type=['speak'], text='What languages do you speak?', pause={'after': 10})
        self.graph.add_edge('Node_5', 'Node_7', label='yes')
        self.graph.add_edge('Node_7', 'Node_8', label='Node_7_8')
        self.graph.add_node('Node_8', type=['speak'], text='Would you like to play with me? #¿Quieren jugar conmigo? #', pause={'after': 5})
        self.graph.add_edge('Node_8', 'Node_9', label='Node_8_9')
        self.graph.add_node('Node_9', type=['speak'], text='#¡Excelente!#')
        self.graph.add_edge('Node_9', 'Node_10', label='Node_9_10')
        self.graph.add_node('Node_10', type=['speak'], text='How do you say hello in Spanish?')
        self.graph.add_edge('Node_10', 'Node_11', label='Node_10_11')
        self.graph.add_node('Node_11', type=['move', 'puase'], motors='look_from_side_to_side')
        self.graph.add_edge('Node_11', 'Node_12', label='Node_11_12')
        self.graph.add_node('Node_12', type=['speak', 'move'], text='That`s right. # ¡hola! # Let`s all waive our hands and say it together:#¡hola!#', motors='wave_hello', pause={'after': 3})
        self.graph.add_edge('Node_12', 'Node_13', label='Node_12_13')
        self.graph.add_node('Node_13', type=['speak', 'move'], text='If you want to play, raise your hands! # ¡Si quieren jugar, levanten las manos! #', motors='arms_up', pause={'after': 2})
        self.graph.add_edge('Node_13', 'Node_14', label='Node_13_14')
        self.graph.add_node('Node_14', type=['speak'], text='High!', pause={'after': 1})
        self.graph.add_edge('Node_14', 'Node_15', label='Node_14_15')
        self.graph.add_node('Node_15', type=['speak'], text='Higher!', pause={'after': 1})
        self.graph.add_edge('Node_15', 'Node_16', label='Node_15_16')
        self.graph.add_node('Node_16', type=['speak'], text='This is great! I`m so happy you want to play with me.')
        self.graph.add_edge('Node_16', 'Node_17', label='Node_16_17')
        self.graph.add_node('Node_17', type=['audio'], audio='laugh.wav', pause={'after': 2})
        self.graph.add_edge('Node_17', 'Node_18', label='Node_17_18')
        self.graph.add_node('Node_18', type=['speak', 'move', 'face'], text='Can you see? You have a bin with LEGO blocks and LEGO figures on the table.', motors='arms_down', face=basic_sequences['look_down'])
        self.graph.add_edge('Node_18', 'Node_19', label='Node_18_19')
        self.graph.add_node('Node_19', type=['speak'], text='Can you find a LEGO figure that you like? Everyone can choose one LEGO figure and decorate it. # Elijan una figura LEGO y decórenla. #')
        self.graph.add_edge('Node_19', 'Node_20', label='Node_19_20')
        self.graph.add_node('Node_20', type=['speak', 'face'], text='Show your figure to your friends. When you are done, raise the black and white card you have in front of you. # Muestra tu figura a tus amigos. Cuando termines, levanta la tarjeta con la carita sonriente que tienes frente a ti. #', face=basic_sequences['idle'])
        self.graph.add_edge('Node_20', 'Node_21', label='Node_20_21')
        self.graph.add_node('Node_21', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_22', type=['speak'], text='I see you are having fun. Let me know when you are done by raising the card.')
        self.graph.add_edge('Node_21', 'Node_22', label='no')
        self.graph.add_edge('Node_22', 'Node_21', label='Node_22_21')
        self.graph.add_node('Node_23', type=['speak'], text='Great!')
        self.graph.add_edge('Node_21', 'Node_23', label='yes')
        self.graph.add_edge('Node_23', 'Node_24', label='Node_23_24')
        self.graph.add_node('Node_24', type=['speak'], text='Did you pick a boy or a girl? # ¿Escogiste a un niño o una niña? #', pause={'after': 1})
        self.graph.add_edge('Node_24', 'Node_25', label='Node_24_25')
        self.graph.add_node('Node_25', type=['speak'], text='What kind of hair do they have? Curly? Straight? Short? Long? # ¿Qué tipo de cabello tiene? ¿Rizado? ¿Lacio? #', pause={'after': 1})
        self.graph.add_edge('Node_25', 'Node_26', label='Node_25_26')
        self.graph.add_node('Node_26', type=['speak'], text='What color is their shirt? # ¿De qué color es su camiseta?#', pause={'after': 1})
        self.graph.add_edge('Node_26', 'Node_27', label='Node_26_27')
        self.graph.add_node('Node_27', type=['speak', 'show'], text='Look, I picked a girl with brown hair and a blue shirt.', image='../Assets/Bilingual_Lego/blue_figure.png')
        self.graph.add_edge('Node_27', 'Node_28', label='Node_27_28')
        self.graph.add_node('Node_28', type=['speak'], text='Blue is my favorite color. #Mira, tiene cabello castaño y una camiseta azul. #')
        self.graph.add_edge('Node_28', 'Node_29', label='Node_28_29')
        self.graph.add_node('Node_29', type=['speak', 'move'], text='Show your friends your figure and tell them what you picked.', motors='look_from_side_to_side', pause={'after': 10})
        self.graph.add_edge('Node_29', 'Node_30', label='Node_29_30')
        self.graph.add_node('Node_30', type=['speak', 'move'], text='Does your figure have a name? Share it with your friends! ¿Tu figura tiene nombre? ¡Compártelo con tus amigos!.', motors='look_from_side_to_side', pause={'after': 10})
        self.graph.add_edge('Node_30', 'Node_31', label='Node_30_31')
        self.graph.add_node('Node_31', type=['speak'], text='Now, we`re ready to start! # ¡Vamos a empezar!#')
        self.graph.add_edge('Node_31', 'Node_32', label='Node_31_32')
        self.graph.add_node('Node_32', type=['speak', 'move'], text='Today we`re going to build a Ferris wheel. # Hoy vamos a construir una rueda de la fortuna.#', motors='arms_up')
        self.graph.add_edge('Node_32', 'Node_33', label='Node_32_33')
        self.graph.add_node('Node_33', type=['speak'], text='Do you know what a Ferris wheel is? #¿Saben qué es?#')
        self.graph.add_edge('Node_33', 'Node_34', label='Node_33_34')
        self.graph.add_node('Node_34', type=['hear'], words='["yes", "no", "[unk]"]')
        self.graph.add_node('Node_35', type=['speak'], text='Ferris wheels are so much fun! I love going on them and spinning round and round.')
        self.graph.add_edge('Node_34', 'Node_35', label='yes')
        self.graph.add_edge('Node_35', 'Node_38', label='Node_35_38')
        self.graph.add_node('Node_36', type=['speak'], text='Who can tell us? What is a Ferris wheel? ¿Quién puede decirnos?¿Qué es una rueda de la fortuna?')
        self.graph.add_edge('Node_34', 'Node_36', label='no')
        self.graph.add_edge('Node_36', 'Node_38', label='Node_36_38')
        self.graph.add_node('Node_37', type=['speak'], text='Ferris wheels are so much fun! I love going on them and spinning round and round.')
        self.graph.add_edge('Node_34', 'Node_37', label='timeout')
        self.graph.add_edge('Node_37', 'Node_38', label='Node_37_38')
        self.graph.add_node('Node_38', type=['speak', 'move'], text='Yes! A Ferris wheel is a big wheel that spins round and round. Or in Spanish, #gira#, round and round.', motors='arms_circle')
        self.graph.add_edge('Node_38', 'Node_39', label='Node_38_39')
        self.graph.add_node('Node_39', type=['speak'], text='You can find Ferris wheels in carnivals! I love them! ¡Las puedes encontrar en ferias! ¡Me encantan!#')
        self.graph.add_edge('Node_39', 'Node_40', label='Node_39_40')
        self.graph.add_node('Node_40', type=['audio'], audio='laugh.wav')
        self.graph.add_edge('Node_40', 'Node_41', label='Node_40_41')
        self.graph.add_node('Node_41', type=['speak'], text='Did you know? People say “Ferris wheel” in different ways in Spanish, depending on where they live.', pause={'after': 1})
        self.graph.add_edge('Node_41', 'Node_42', label='Node_41_42')
        self.graph.add_node('Node_42', type=['speak'], text='In Mexico, many people say #rueda de la fortuna#. In Argentina, they say #vuelta al mundo#. In Spain, they often say #noria#. Some people say #rueda gigante#.', pause={'after': 1})
        self.graph.add_edge('Node_42', 'Node_43', label='Node_42_43')
        self.graph.add_node('Node_43', type=['find'], what='face', timeout=5)
        self.graph.add_node('Node_44', type=['speak'], text='What about you?')
        self.graph.add_edge('Node_43', 'Node_44', label='no')
        self.graph.add_edge('Node_44', 'Node_46', label='Node_44_46')
        self.graph.add_node('Node_45', type=['speak'], text='What about you?')
        self.graph.add_edge('Node_43', 'Node_45', label='yes')
        self.graph.add_edge('Node_45', 'Node_46', label='Node_45_46')
        self.graph.add_node('Node_46', type=['speak'], text='How do you say “Ferris wheel” at home or in your family`s language? #¿Y ustedes? ¿Cómo lo dicen en su casa o en su idioma?#', pause={'after': 10})
        self.graph.add_edge('Node_46', 'Node_47', label='Node_46_47')
        self.graph.add_node('Node_47', type=['speak', 'move'], text='Wow, so many ways to say it! Isn`t it cool that we can learn from each other? #¡Qué bonito aprender diferentes palabras entre todos!#', motors='arms_up')
        self.graph.add_edge('Node_47', 'Node_48', label='Node_47_48')
        self.graph.add_node('Node_48', type=['find'], what='face', timeout=5)
        self.graph.add_node('Node_49', type=['speak'], text='Have you ever been on a Ferris wheel?')
        self.graph.add_edge('Node_48', 'Node_49', label='no')
        self.graph.add_edge('Node_49', 'Node_51', label='Node_49_51')
        self.graph.add_node('Node_50', type=['speak'], text='Have you ever been on a Ferris wheel?')
        self.graph.add_edge('Node_48', 'Node_50', label='yes')
        self.graph.add_edge('Node_50', 'Node_51', label='Node_50_51')
        self.graph.add_node('Node_51', type=['speak'], text='Tell your friends. ¿Alguna vez has subido a una rueda de la fortuna? Cuéntenle a sus amigos.#', pause={'after': 10})
        self.graph.add_edge('Node_51', 'Node_52', label='Node_51_52')
        self.graph.add_node('Node_52', type=['speak', 'move'], text='Today we`ll build a big Ferris wheel together for our LEGO friends!  # ¡Hoy construiremos una gran rueda de la fortuna para nuestros amigos LEGO juntos! #', motors='home')
        self.graph.add_edge('Node_52', 'Node_53', label='Node_52_53')
        self.graph.add_node('Node_53', type=['speak'], text='We can build together! Everyone will have an important role!', pause={'after': 1})
        self.graph.add_edge('Node_53', 'Node_54', label='Node_53_54')
        self.graph.add_node('Node_54', type=['speak', 'move', 'face'], text='Look at the bin at the center of your table! It has all the pieces.', motors='arms_down', face=basic_sequences['look_down'])
        self.graph.add_edge('Node_54', 'Node_55', label='Node_54_55')
        self.graph.add_node('Node_55', type=['speak'], text='So let`s get started! # Miren la caja en el centro de la mesa. ¡Tiene todas las piezas que necesitamos! #')
        self.graph.add_edge('Node_55', 'Node_56', label='Node_55_56')
        self.graph.add_node('Node_56', type=['speak'], text='Are you ready? # ¿Listos?#', pause={'after': 3})
        self.graph.add_edge('Node_56', 'Node_57', label='Node_56_57')
        self.graph.add_node('Node_57', type=['speak'], text='Great! # ¡Muy bien!')
        self.graph.add_edge('Node_57', 'Node_58', label='Node_57_58')
        self.graph.add_node('Node_58', type=['speak', 'move'], text='Who wants to be the finder in this step?, #¿Quién quiere ser el buscador o la buscadora en este paso?#', motors='look_from_side_to_side')
        self.graph.add_edge('Node_58', 'Node_59', label='Node_58_59')
        self.graph.add_node('Node_59', type=['speak', 'show'], text='Can you find the yellow controller block #el bloque controlador amarillo# and four green pins #y cuatro clavijas verdes#?', image='../Assets/Bilingual_Lego/ferris_step_01.png')
        self.graph.add_edge('Node_59', 'Node_60', label='Node_59_60')
        self.graph.add_node('Node_60', type=['speak', 'show'], text='When you are done, raise your cards. #Cuando terminen, levanten sus tarjetas.#', image='../Assets/Bilingual_Lego/ferris_step_01.png')
        self.graph.add_edge('Node_60', 'Node_61', label='Node_60_61')
        self.graph.add_node('Node_61', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_62', type=['speak', 'show'], text='Still searching? Take your time.', image='../Assets/Bilingual_Lego/ferris_step_01.png')
        self.graph.add_edge('Node_61', 'Node_62', label='no')
        self.graph.add_edge('Node_62', 'Node_61', label='Node_62_61')
        self.graph.add_node('Node_63', type=['speak'], text='Great! That`s our yellow controller!')
        self.graph.add_edge('Node_61', 'Node_63', label='yes')
        self.graph.add_edge('Node_63', 'Node_64', label='Node_63_64')
        self.graph.add_node('Node_64', type=['speak'], text='Do you remember how to say yellow in Spanish?', pause={'after': 4})
        self.graph.add_edge('Node_64', 'Node_65', label='Node_64_65')
        self.graph.add_node('Node_65', type=['speak'], text='It is #amarillo#, yellow.')
        self.graph.add_edge('Node_65', 'Node_66', label='Node_65_66')
        self.graph.add_node('Node_66', type=['speak'], text='Let`s say it together: #amarillo#, yellow!', pause={'after': 2})
        self.graph.add_edge('Node_66', 'Node_67', label='Node_66_67')
        self.graph.add_node('Node_67', type=['audio'], audio='laugh.wav')
        self.graph.add_edge('Node_67', 'Node_68', label='Node_67_68')
        self.graph.add_node('Node_68', type=['speak', 'move'], text='Now, we need a builder for this step. #Ahora necesitamos un constructor o una constructora#.', motors='look_from_side_to_side')
        self.graph.add_edge('Node_68', 'Node_69', label='Node_68_69')
        self.graph.add_node('Node_69', type=['speak'], text='Who will it be? Remember, we will switch roles so everyone gets a chance to play all the roles! #Recuerden, vamos a cambiar los roles para que todos tengan la oportunidad de jugar todos los roles.#', pause={'after': 3})
        self.graph.add_edge('Node_69', 'Node_70', label='Node_69_70')
        self.graph.add_node('Node_70', type=['speak', 'show'], text='Now connect the controller to the gray rectangular LEGO plate #constructor, conecta el controlador a la placa. Es gris y rectangular.#. the base.', image='../Assets/Bilingual_Lego/ferris_step_02.png')
        self.graph.add_edge('Node_70', 'Node_71', label='Node_70_71')
        self.graph.add_node('Node_71', type=['speak'], text='Now we need an assistant.')
        self.graph.add_edge('Node_71', 'Node_72', label='Node_71_72')
        self.graph.add_node('Node_72', type=['find'], what='face', timeout=5)
        self.graph.add_node('Node_73', type=['speak'], text='Who can hold the base while the builder clicks the controller in?')
        self.graph.add_edge('Node_72', 'Node_73', label='no')
        self.graph.add_edge('Node_73', 'Node_75', label='Node_73_75')
        self.graph.add_node('Node_74', type=['speak'], text='Who can hold the base while the builder clicks the controller in?')
        self.graph.add_edge('Node_72', 'Node_74', label='yes')
        self.graph.add_edge('Node_74', 'Node_75', label='Node_74_75')
        self.graph.add_node('Node_75', type=['speak'], text='#Una persona sostiene la base mientras la otra encaja el controlador.#', pause={'after': 3})
        self.graph.add_edge('Node_75', 'Node_76', label='Node_75_76')
        self.graph.add_node('Node_76', type=['speak', 'show'], text='Raise your card when you are ready. #Levanta tu tarjeta cuando estés listo.#', image='../Assets/Bilingual_Lego/ferris_step_02.png')
        self.graph.add_edge('Node_76', 'Node_77', label='Node_76_77')
        self.graph.add_node('Node_77', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_78', type=['speak'], text='Not quite done? I will wait. # ¿Todavía no? Aquí espero.#')
        self.graph.add_edge('Node_77', 'Node_78', label='no')
        self.graph.add_edge('Node_78', 'Node_77', label='Node_78_77')
        self.graph.add_node('Node_79', type=['speak'], text='Excellent teamwork! # ¡Buen trabajo en equipo!#')
        self.graph.add_edge('Node_77', 'Node_79', label='yes')
        self.graph.add_edge('Node_79', 'Node_80', label='Node_79_80')
        self.graph.add_node('Node_80', type=['speak'], text='Oh, do you remember how to say gray in Spanish?', pause={'after': 4})
        self.graph.add_edge('Node_80', 'Node_81', label='Node_80_81')
        self.graph.add_node('Node_81', type=['speak'], text='Great! # ¡Muy bien!')
        self.graph.add_edge('Node_81', 'Node_82', label='Node_81_82')
        self.graph.add_node('Node_82', type=['speak'], text='Let`s say it together: #gris#, gray.')
        self.graph.add_edge('Node_82', 'Node_83', label='Node_82_83')
        self.graph.add_node('Node_83', type=['audio', 'move'], audio='laugh.wav', motors='home')
        self.graph.add_edge('Node_83', 'Node_84', label='Node_83_84')
        self.graph.add_node('Node_84', type=['speak'], text='This tower is very important. In Spanish we say: #un torre#, a tower. This tower is 3 blocks high!')
        self.graph.add_edge('Node_84', 'Node_85', label='Node_84_85')
        self.graph.add_node('Node_85', type=['speak'], text='Who can remind me how we count to three in Spanish?', pause={'after': 5})
        self.graph.add_edge('Node_85', 'Node_86', label='Node_85_86')
        self.graph.add_node('Node_86', type=['speak'], text='#uno, dos, tres.# One, two, three.')
        self.graph.add_edge('Node_86', 'Node_87', label='Node_86_87')
        self.graph.add_node('Node_87', type=['speak', 'move'], text='Let`s show what a tower looks like with our hands! Reach up tall like a tower, #como una torre!#', motors='arms_up')
        self.graph.add_edge('Node_87', 'Node_88', label='Node_87_88')
        self.graph.add_node('Node_88', type=['find'], what='face', timeout=5)
        self.graph.add_node('Node_89', type=['speak'], text='How do you say “tower” in your language?')
        self.graph.add_edge('Node_88', 'Node_89', label='no')
        self.graph.add_edge('Node_89', 'Node_91', label='Node_89_91')
        self.graph.add_node('Node_90', type=['speak'], text='How do you say “tower” in your language?')
        self.graph.add_edge('Node_88', 'Node_90', label='yes')
        self.graph.add_edge('Node_90', 'Node_91', label='Node_90_91')
        self.graph.add_node('Node_91', type=['speak', 'move'], text='# ¿Cómo se dice “tower” en tu idioma?#  Can you teach your friends? # ¿Quieres enseñarle a tus amigos?#', motors='arms_down', pause={'after': 5})
        self.graph.add_edge('Node_91', 'Node_92', label='Node_91_92')
        self.graph.add_node('Node_92', type=['speak', 'show'], text='Now, stack three bricks to build a tower. First put the yellow part #coloca la parte amarilla# on the gray base #sobre la base gris#. #', image='../Assets/Bilingual_Lego/ferris_step_03.png', pause={'after': 5})
        self.graph.add_edge('Node_92', 'Node_93', label='Node_92_93')
        self.graph.add_node('Node_93', type=['speak', 'show'], text='Then stack one red brick #un ladrillo rojo# as base and three bricks #tres ladrillos verdes#, one on top of the other #uno encima del otro#.', image='../Assets/Bilingual_Lego/ferris_step_05.png')
        self.graph.add_edge('Node_93', 'Node_94', label='Node_93_94')
        self.graph.add_node('Node_94', type=['speak'], text='You can take turns: one stacks, the other one counts. Then switch!  #Pueden turnarse: uno apila y el otro cuenta.#', pause={'after': 3})
        self.graph.add_edge('Node_94', 'Node_95', label='Node_94_95')
        self.graph.add_node('Node_95', type=['speak', 'show'], text='When it`s done, raise your cards. # Cuando terminen, levanten sus tarjetas. #', image='../Assets/Bilingual_Lego/ferris_step_05.png')
        self.graph.add_edge('Node_95', 'Node_96', label='Node_95_96')
        self.graph.add_node('Node_96', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_97', type=['speak'], text='Not quite done? I will wait. # ¿Todavía no? Aquí espero.#')
        self.graph.add_edge('Node_96', 'Node_97', label='no')
        self.graph.add_edge('Node_97', 'Node_96', label='Node_97_96')
        self.graph.add_node('Node_98', type=['speak'], text='Excellent teamwork! # ¡Buen trabajo!#')
        self.graph.add_edge('Node_96', 'Node_98', label='yes')
        self.graph.add_edge('Node_98', 'Node_99', label='Node_98_99')
        self.graph.add_node('Node_99', type=['audio'], audio='laugh.wav')
        self.graph.add_edge('Node_99', 'Node_100', label='Node_99_100')
        self.graph.add_node('Node_100', type=['speak', 'move'], text='Time to add the second tower!', motors='arms_up_and_down')
        self.graph.add_edge('Node_100', 'Node_101', label='Node_100_101')
        self.graph.add_node('Node_101', type=['speak'], text='What parts do we need to build the tower? Who wants to be the finder? #El buscador o la buscadora?#', pause={'after': 3})
        self.graph.add_edge('Node_101', 'Node_102', label='Node_101_102')
        self.graph.add_node('Node_102', type=['speak', 'show'], text='Great! Find the yellow plate and these two orange yellow pieces. #la segunda torre amarilla, la placa amarilla y dos piezas pequeñas naranjas #.', image='../Assets/Bilingual_Lego/ferris_step_08.png')
        self.graph.add_edge('Node_102', 'Node_103', label='Node_102_103')
        self.graph.add_node('Node_103', type=['speka', 'show'], image='../Assets/Bilingual_Lego/ferris_step_08.png')
        self.graph.add_edge('Node_103', 'Node_104', label='Node_103_104')
        self.graph.add_node('Node_104', type=['speak', 'move'], text='Are we ready to build? Who will be the builder this time? El constructor o la constructora?', motors='look_from_side_to_side', pause={'after': 3})
        self.graph.add_edge('Node_104', 'Node_105', label='Node_104_105')
        self.graph.add_node('Node_105', type=['speak', 'show'], text='Put the tower together! The builder can hold the base plate while the assistant presses the tower down. #El constructor puede sostener la base mientras el assistente presiona la torre hacia abajo#', image='../Assets/Bilingual_Lego/ferris_step_08.png')
        self.graph.add_edge('Node_105', 'Node_106', label='Node_105_106')
        self.graph.add_node('Node_106', type=['speak', 'show'], text='Let`s check and see: does the tower look right? Is it the same as in the picture? ¿La torre se parece a la que está en la foto? Raise your cards.  # ¿¿Está conectado? Levanten sus tarjetas. #', image='../Assets/Bilingual_Lego/ferris_step_08.png')
        self.graph.add_edge('Node_106', 'Node_107', label='Node_106_107')
        self.graph.add_node('Node_107', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_108', type=['speak'], text='Still building? I will wait. ¿Todavía no? Aquí espero.#')
        self.graph.add_edge('Node_107', 'Node_108', label='no')
        self.graph.add_edge('Node_108', 'Node_107', label='Node_108_107')
        self.graph.add_node('Node_109', type=['speak'], text='Great! # ¡Muy bien! #')
        self.graph.add_edge('Node_107', 'Node_109', label='yes')
        self.graph.add_edge('Node_109', 'Node_110', label='Node_109_110')
        self.graph.add_node('Node_110', type=['speak'], text='By the way, do you remember how to say yellow in Spanish?', pause={'after': 3})
        self.graph.add_edge('Node_110', 'Node_111', label='Node_110_111')
        self.graph.add_node('Node_111', type=['speak'], text='It`s #amarillo#, yellow.')
        self.graph.add_edge('Node_111', 'Node_112', label='Node_111_112')
        self.graph.add_node('Node_112', type=['speak'], text='The second tower is ready. Great job. # la ¡Una torre está lista! Muy buen trabajo.#')
        self.graph.add_edge('Node_112', 'Node_113', label='Node_112_113')
        self.graph.add_node('Node_113', type=['audio'], audio='laugh.wav')
        self.graph.add_edge('Node_113', 'Node_114', label='Node_113_114')
        self.graph.add_node('Node_114', type=['speak', 'show'], text='Who wants to be the finder now? What pieces do we need to build the light? Take a look!', image='../Assets/Bilingual_Lego/ferris_step_09.png', pause={'after': 5})
        self.graph.add_edge('Node_114', 'Node_115', label='Node_114_115')
        self.graph.add_node('Node_115', type=['speak'], text='Do we have everything we need? #¿Tenemos todo lo que necesitamos?#')
        self.graph.add_edge('Node_115', 'Node_116', label='Node_115_116')
        self.graph.add_node('Node_116', type=['speak', 'move'], text='Now, whose turn is it to be the builder? Attach the parts and put the light together!', motors='look_from_side_to_side')
        self.graph.add_edge('Node_116', 'Node_117', label='Node_116_117')
        self.graph.add_node('Node_117', type=['speak', 'show'], text='Find the light piece #la pieza de luz# and connect the green pieces to it #conecta las piezas verdes#, similar to the motor. #igual que con el motor.#', image='../Assets/Bilingual_Lego/ferris_step_09.png', pause={'after': 5})
        self.graph.add_edge('Node_117', 'Node_118', label='Node_117_118')
        self.graph.add_node('Node_118', type=['speak'], text='Remember how to say green in Spanish?', pause={'after': 4})
        self.graph.add_edge('Node_118', 'Node_119', label='Node_118_119')
        self.graph.add_node('Node_119', type=['speak'], text='Great! # ¡Muy bien! # It`s #verde#, green.')
        self.graph.add_edge('Node_119', 'Node_120', label='Node_119_120')
        self.graph.add_node('Node_120', type=['speak', 'show'], text='Time to check! Does the light look like in the picture? ¿La luz se ve como en la foto? Raise your cards if you think it`s correct.', image='../Assets/Bilingual_Lego/ferris_step_09.png')
        self.graph.add_edge('Node_120', 'Node_121', label='Node_120_121')
        self.graph.add_node('Node_121', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_122', type=['speak'], text='oh uh! Let`s check again! Is there a mistake? Who can help fix it? ¿Algo anda mal? ¿Quién puede ayudar a arreglarlo?')
        self.graph.add_edge('Node_121', 'Node_122', label='no')
        self.graph.add_edge('Node_122', 'Node_124', label='Node_122_124')
        self.graph.add_node('Node_123', type=['speak'], text='Is the light attached to the base? Like in this picture? ¿La luz se ve como en la foto?')
        self.graph.add_edge('Node_121', 'Node_123', label='yes')
        self.graph.add_edge('Node_123', 'Node_124', label='Node_123_124')
        self.graph.add_node('Node_124', type=['speak', 'show'], text='When the light is attached to the base, hold up your cards. # ¿Cuando esté listo, levanten sus tarjetas. #', image='../Assets/Bilingual_Lego/ferris_step_10.png')
        self.graph.add_edge('Node_124', 'Node_125', label='Node_124_125')
        self.graph.add_node('Node_125', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_126', type=['speak', 'show'], text='Take your time. I will wait here until the light piece is attached.', image='../Assets/Bilingual_Lego/ferris_step_10.png')
        self.graph.add_edge('Node_125', 'Node_126', label='no')
        self.graph.add_edge('Node_126', 'Node_125', label='Node_126_125')
        self.graph.add_node('Node_127', type=['speak'], text='That was great teamwork!')
        self.graph.add_edge('Node_125', 'Node_127', label='yes')
        self.graph.add_edge('Node_127', 'Node_128', label='Node_127_128')
        self.graph.add_node('Node_128', type=['speak'], text='Awesome!  # ¡Muy bien! #')
        self.graph.add_edge('Node_128', 'Node_129', label='Node_128_129')
        self.graph.add_node('Node_129', type=['speak', 'show'], text='Now let`s find the motor and attach green pins to it. #Ahora, encuentra el motor y colócale los pasadores verdes.#', image='../Assets/Bilingual_Lego/ferris_step_11.png', pause={'after': 5})
        self.graph.add_edge('Node_129', 'Node_130', label='Node_129_130')
        self.graph.add_node('Node_130', type=['speak', 'move'], text='Who wants to be the finder now? Raise your card! ¿Quién quiere ser el buscador ahora? ¡Levanta tu tarjeta!', motors='look_from_side_to_side', pause={'after': 6})
        self.graph.add_edge('Node_130', 'Node_131', label='Node_130_131')
        self.graph.add_node('Node_131', type=['speak'], text='Oh! Two friends want to be finders. I love it when we collaborate! You can work together to find all the pieces we need to build the motor!')
        self.graph.add_edge('Node_131', 'Node_132', label='Node_131_132')
        self.graph.add_node('Node_132', type=['speak', 'show'], text='Great! find the motor, attach green pins to it.', image='../Assets/Bilingual_Lego/ferris_step_11.png', pause={'after': 5})
        self.graph.add_edge('Node_132', 'Node_133', label='Node_132_133')
        self.graph.add_node('Node_133', type=['speak', 'show'], text='Now, who wants to attach the motor to the tower?  #¿Quien quierre adjuntar el motor al torre?# Make sure it is attached in the correct spot!', image='../Assets/Bilingual_Lego/ferris_step_12.png')
        self.graph.add_edge('Node_133', 'Node_134', label='Node_133_134')
        self.graph.add_node('Node_134', type=['speak', 'show'], text='Let`s check together! If you think the motor is attached the right way, raise your cards!', image='../Assets/Bilingual_Lego/ferris_step_12.png')
        self.graph.add_edge('Node_134', 'Node_135', label='Node_134_135')
        self.graph.add_node('Node_135', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_136', type=['speak'], text='Let me know when it is attached. I will wait! #Espero aqui#')
        self.graph.add_edge('Node_135', 'Node_136', label='no')
        self.graph.add_edge('Node_136', 'Node_135', label='Node_136_135')
        self.graph.add_node('Node_137', type=['speak'], text='That was great teamwork! #¡Eso fue un gran trabajo en equipo!#')
        self.graph.add_edge('Node_135', 'Node_137', label='yes')
        self.graph.add_edge('Node_137', 'Node_138', label='Node_137_138')
        self.graph.add_node('Node_138', type=['speak'], text='By the way, do you know how to say “motor" in Spanish?')
        self.graph.add_edge('Node_138', 'Node_139', label='Node_138_139')
        self.graph.add_node('Node_139', type=['hear'], words='["yes", "motor", "no", "[unk]"]')
        self.graph.add_node('Node_140', type=['speak'], text='That`s right!  It`s the same word. Just the way it is said is a bit different! #El motor#')
        self.graph.add_edge('Node_139', 'Node_140', label='yes')
        self.graph.add_edge('Node_140', 'Node_141', label='Node_140_141')
        self.graph.add_node('Node_141', type=['speak'], text='That`s right!  It`s the same word. Just the way it is said is a bit different! #El motor#')
        self.graph.add_edge('Node_139', 'Node_141', label='motor')
        self.graph.add_edge('Node_141', 'Node_144', label='Node_141_144')
        self.graph.add_node('Node_142', type=['speak'], text='It`s #el motor#. It`s the same word. Just the way it is said is a bit different! #El motor#')
        self.graph.add_edge('Node_139', 'Node_142', label='no')
        self.graph.add_edge('Node_142', 'Node_144', label='Node_142_144')
        self.graph.add_node('Node_143', type=['speak'], text='It`s #el motor#. It`s the same word. Just the way it is said is a bit different! #El motor#')
        self.graph.add_edge('Node_139', 'Node_143', label='timeout')
        self.graph.add_edge('Node_143', 'Node_144', label='Node_143_144')
        self.graph.add_node('Node_144', type=['speak'], text='Let`s say it all together: #el motor# motor.', pause={'after': 2})
        self.graph.add_edge('Node_144', 'Node_145', label='Node_144_145')
        self.graph.add_node('Node_145', type=['speak'], text='The wheel is really coming together!', pause={'after': 2})
        self.graph.add_edge('Node_145', 'Node_146', label='Node_145_146')
        self.graph.add_node('Node_146', type=['speak'], text='Now, your figures need a way to reach the ferris wheel. #Tus figuras necesitan llegar a la rueda de la fortuna.#')
        self.graph.add_edge('Node_146', 'Node_147', label='Node_146_147')
        self.graph.add_node('Node_147', type=['speak'], text='Who has an idea?')
        self.graph.add_edge('Node_147', 'Node_148', label='Node_147_148')
        self.graph.add_node('Node_148', type=['find'], what='face', timeout=5)
        self.graph.add_node('Node_149', type=['speak'], text='Tell your friends!! #¿Tienes una idea? ¡Dísela a tus amigos!#', pause={'after': 5})
        self.graph.add_edge('Node_148', 'Node_149', label='no')
        self.graph.add_edge('Node_149', 'Node_151', label='Node_149_151')
        self.graph.add_node('Node_150', type=['speak'], text='Tell your friends!! #¿Tienes una idea? ¡Dísela a tus amigos!#', pause={'after': 5})
        self.graph.add_edge('Node_148', 'Node_150', label='yes')
        self.graph.add_edge('Node_150', 'Node_151', label='Node_150_151')
        self.graph.add_node('Node_151', type=['speak'], text='How about building stairs? ¿Qué tal si construyen unas escaleras?"', pause={'after': 2})
        self.graph.add_edge('Node_151', 'Node_152', label='Node_151_152')
        self.graph.add_node('Node_152', type=['speak', 'move'], text='Who`s turn is it to be the finder?', motors='look_from_side_to_side')
        self.graph.add_edge('Node_152', 'Node_153', label='Node_152_153')
        self.graph.add_node('Node_153', type=['speak', 'show'], text='Find the yellow brick # el ladrillo amarillo# and the blue tiles #y las piezas azules# in the picture! Raise your card when you`re done!', image='../Assets/Bilingual_Lego/ferris_step_13.png')
        self.graph.add_edge('Node_153', 'Node_154', label='Node_153_154')
        self.graph.add_node('Node_154', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_155', type=['speak'], text='Let me know when you find it. I will wait! #Espero aqui#')
        self.graph.add_edge('Node_154', 'Node_155', label='no')
        self.graph.add_edge('Node_155', 'Node_154', label='Node_155_154')
        self.graph.add_node('Node_156', type=['speak'], text='That was great teamwork! #¡Eso fue un gran trabajo en equipo!#')
        self.graph.add_edge('Node_154', 'Node_156', label='yes')
        self.graph.add_edge('Node_156', 'Node_157', label='Node_156_157')
        self.graph.add_node('Node_157', type=['speak'], text='Now, let`s build the stairs! Who`s turn is it to be the builder? #¿Quien es el constructor or la constructora?#', pause={'after': 3})
        self.graph.add_edge('Node_157', 'Node_158', label='Node_157_158')
        self.graph.add_node('Node_158', type=['speak'], text='Connect the yellow brick #el ladrillo amarillo# and the blue tiles #y las piezas azules#', pause={'after': 5})
        self.graph.add_edge('Node_158', 'Node_159', label='Node_158_159')
        self.graph.add_node('Node_159', type=['speak'], text='Then connect two more blue tiles. #Conecten dos piezas azules más.#')
        self.graph.add_edge('Node_159', 'Node_160', label='Node_159_160')
        self.graph.add_node('Node_160', type=['speak', 'show'], text='When they`re all connected, raise your card. #  ¿Cuando esté listo, levanten sus tarjetas. #', image='../Assets/Bilingual_Lego/ferris_step_14.png')
        self.graph.add_edge('Node_160', 'Node_161', label='Node_160_161')
        self.graph.add_node('Node_161', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_162', type=['speak'], text='Still fixing the stairs? I will wait until you are done.')
        self.graph.add_edge('Node_161', 'Node_162', label='no')
        self.graph.add_edge('Node_162', 'Node_161', label='Node_162_161')
        self.graph.add_node('Node_163', type=['speak'], text='You built the blue stairs #escaleras#! What a super team!')
        self.graph.add_edge('Node_161', 'Node_163', label='yes')
        self.graph.add_edge('Node_163', 'Node_164', label='Node_163_164')
        self.graph.add_node('Node_164', type=['speak'], text='I love the color blue. Remember how to say blue in Spanish?', pause={'after': 4})
        self.graph.add_edge('Node_164', 'Node_165', label='Node_164_165')
        self.graph.add_node('Node_165', type=['speak'], text='It`s #azul#, blue. My favorite color!')
        self.graph.add_edge('Node_165', 'Node_166', label='Node_165_166')
        self.graph.add_node('Node_166', type=['audio'], audio='laugh.wav')
        self.graph.add_edge('Node_166', 'Node_167', label='Node_166_167')
        self.graph.add_node('Node_167', type=['speak', 'show'], text='Okay, now find the rod #encuentra la varilla# and put it in the motor #y colócala en el motor#.', image='../Assets/Bilingual_Lego/ferris_step_15.png')
        self.graph.add_edge('Node_167', 'Node_168', label='Node_167_168')
        self.graph.add_node('Node_168', type=['speak', 'show'], text='That will make the ferris wheel turn. #Eso hará que la rueda de la fortuna gire.#', image='../Assets/Bilingual_Lego/ferris_step_15.png', pause={'after': 15})
        self.graph.add_edge('Node_168', 'Node_169', label='Node_168_169')
        self.graph.add_node('Node_169', type=['speak', 'move'], text='Can you make your hands spin like a wheel?', motors='arms_circle', pause={'after': 5})
        self.graph.add_edge('Node_169', 'Node_170', label='Node_169_170')
        self.graph.add_node('Node_170', type=['speak'], text='How do you say “spin” in Spanish?', pause={'after': 4})
        self.graph.add_edge('Node_170', 'Node_171', label='Node_170_171')
        self.graph.add_node('Node_171', type=['speak'], text='Yes! #Girar#, spin! Great! # ¡Muy bien! #')
        self.graph.add_edge('Node_171', 'Node_172', label='Node_171_172')
        self.graph.add_node('Node_172', type=['speak'], text='Nice! Now we build the arms of the ferris wheel. #Los brazos de la rueda#')
        self.graph.add_edge('Node_172', 'Node_173', label='Node_172_173')
        self.graph.add_node('Node_173', type=['speaker'], pause={'after': 3})
        self.graph.add_edge('Node_173', 'Node_174', label='Node_173_174')
        self.graph.add_node('Node_174', type=['speak'], text='Remember we are always switching roles so everyone gets a chance to help!', pause={'after': 5})
        self.graph.add_edge('Node_174', 'Node_175', label='Node_174_175')
        self.graph.add_node('Node_175', type=['speaker', 'show'], image='../Assets/Bilingual_Lego/ferris_step_16.png', pause={'after': 10})
        self.graph.add_edge('Node_175', 'Node_176', label='Node_175_176')
        self.graph.add_node('Node_176', type=['speak', 'show'], text='Now, connect the green pieces #las piezas verdes# to the round wheel center #al centro redondo de la rueda# to form an X.', image='../Assets/Bilingual_Lego/ferris_step_17.png')
        self.graph.add_edge('Node_176', 'Node_177', label='Node_176_177')
        self.graph.add_node('Node_177', type=['speak', 'show'], text='Holder, you can now hold the wheel while your friend adds the arms #mientras su compañero agrega los brazos#. When they`re all connected, raise your cards. #Cuando todo esté conectado, levanten sus tarjetas.#', image='../Assets/Bilingual_Lego/ferris_step_17.png')
        self.graph.add_edge('Node_177', 'Node_178', label='Node_177_178')
        self.graph.add_node('Node_178', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_179', type=['speak', 'show'], text='Need more time? I will wait until you are done. #¿Todavía no? Aquí espero.#', image='../Assets/Bilingual_Lego/ferris_step_17.png')
        self.graph.add_edge('Node_178', 'Node_179', label='no')
        self.graph.add_edge('Node_179', 'Node_178', label='Node_179_178')
        self.graph.add_node('Node_180', type=['speak'], text='You made an X! What a super team!')
        self.graph.add_edge('Node_178', 'Node_180', label='yes')
        self.graph.add_edge('Node_180', 'Node_181', label='Node_180_181')
        self.graph.add_node('Node_181', type=['speak', 'move'], text='Now let`s complete the ferris wheel!', motors='arms_up', pause={'after': 1})
        self.graph.add_edge('Node_181', 'Node_182', label='Node_181_182')
        self.graph.add_node('Node_182', type=['speak', 'move', 'show'], text='Let`s look at the instructions together? What is the part we need for this step? Everyone can look together now!', motors='home', image='../Assets/Bilingual_Lego/ferris_step_18.png')
        self.graph.add_edge('Node_182', 'Node_183', label='Node_182_183')
        self.graph.add_node('Node_183', type=['speak', 'show'], text='Put one more purple circle. #un círculo morado.# Choose who builds this step! #¡Elijan quién construye este paso!#', image='../Assets/Bilingual_Lego/ferris_step_18.png')
        self.graph.add_edge('Node_183', 'Node_184', label='Node_183_184')
        self.graph.add_node('Node_184', type=['speak', 'show'], text='Builder, raise your card when you`re done! #¡Constructor, levanta tu tarjeta cuando termines!#', image='../Assets/Bilingual_Lego/ferris_step_18.png', pause={'after': 10})
        self.graph.add_edge('Node_184', 'Node_185', label='Node_184_185')
        self.graph.add_node('Node_185', type=['speak', 'show'], text='Then four white pieces #cuatro piezas blancas#. Work together. #Trabajen juntos.#', image='../Assets/Bilingual_Lego/ferris_step_19.png', pause={'after': 10})
        self.graph.add_edge('Node_185', 'Node_186', label='Node_185_186')
        self.graph.add_node('Node_186', type=['speak', 'show'], text='Then a green round piece. #una pieza redonda verde.#', image='../Assets/Bilingual_Lego/ferris_step_20.png', pause={'after': 5})
        self.graph.add_edge('Node_186', 'Node_187', label='Node_186_187')
        self.graph.add_node('Node_187', type=['speak', 'show'], text='And an orange cone. #un cono naranja.#', image='../Assets/Bilingual_Lego/ferris_step_21.png', pause={'after': 10})
        self.graph.add_edge('Node_187', 'Node_188', label='Node_187_188')
        self.graph.add_node('Node_188', type=['speak', 'move'], text='Our wheel is done!', motors='arms_circle', pause={'after': 1})
        self.graph.add_edge('Node_188', 'Node_189', label='Node_188_189')
        self.graph.add_node('Node_189', type=['speka'], pause={'after': 2})
        self.graph.add_edge('Node_189', 'Node_190', label='Node_189_190')
        self.graph.add_node('Node_190', type=['speak'], text='I forgot; how do you say ‘seat` in Spanish again? # Me olvidé. ¿Cómo se dice “seat” en espanol?  #', pause={'after': 4})
        self.graph.add_edge('Node_190', 'Node_191', label='Node_190_191')
        self.graph.add_node('Node_191', type=['speak'], text='#asiento#')
        self.graph.add_edge('Node_191', 'Node_192', label='Node_191_192')
        self.graph.add_node('Node_192', type=['speak', 'show'], text='Oh, that`s right. Now, you need to build four seats, # quatro asientos #.', image='../Assets/Bilingual_Lego/ferris_step_22.png')
        self.graph.add_edge('Node_192', 'Node_193', label='Node_192_193')
        self.graph.add_node('Node_193', type=['speak'], text='One seat for each arm of the wheel and for each lego figure! Let`s work together!')
        self.graph.add_edge('Node_193', 'Node_194', label='Node_193_194')
        self.graph.add_node('Node_194', type=['speak', 'show'], text='Each friend can pick a seat to build! #¡Cada amigo puede elegir un asiento para construir!# Help each other! #¡Ayúdense entre sí!#', image='../Assets/Bilingual_Lego/ferris_step_22.png')
        self.graph.add_edge('Node_194', 'Node_195', label='Node_194_195')
        self.graph.add_node('Node_195', type=['speak', 'show'], text='Let me know when you are done.', image='../Assets/Bilingual_Lego/ferris_step_22.png')
        self.graph.add_edge('Node_195', 'Node_196', label='Node_195_196')
        self.graph.add_node('Node_196', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_197', type=['speak', 'show'], text='Still finalizing those seats? I will wait until you are done. # ¿Todavía terminando esos asientos? Espero aqui #', image='../Assets/Bilingual_Lego/ferris_step_22.png')
        self.graph.add_edge('Node_196', 'Node_197', label='no')
        self.graph.add_edge('Node_197', 'Node_196', label='Node_197_196')
        self.graph.add_node('Node_198', type=['speak'], text='You have the wheel! What a great team!')
        self.graph.add_edge('Node_196', 'Node_198', label='yes')
        self.graph.add_edge('Node_198', 'Node_200', label='Node_198_200')
        self.graph.add_node('Node_199', type=['speak'], text='You have the wheel! What a great team!')
        self.graph.add_edge('Node_196', 'Node_199', label='timeout')
        self.graph.add_edge('Node_199', 'Node_200', label='Node_199_200')
        self.graph.add_node('Node_200', type=['speak'], text='Finally, we are ready to put the wheel on the axle.')
        self.graph.add_edge('Node_200', 'Node_201', label='Node_200_201')
        self.graph.add_node('Node_201', type=['speak'], text='Who will be the builder now? And who can be the holder? #¿Ahora quién será el constructor? ¿Y quién puede ser el que sostiene?#')
        self.graph.add_edge('Node_201', 'Node_202', label='Node_201_202')
        self.graph.add_node('Node_202', type=['find'], what='face', timeout=5)
        self.graph.add_node('Node_203', type=['speak'], text='Now gently slide the wheel onto the axle.')
        self.graph.add_edge('Node_202', 'Node_203', label='no')
        self.graph.add_edge('Node_203', 'Node_205', label='Node_203_205')
        self.graph.add_node('Node_204', type=['speak'], text='Now gently slide the wheel onto the axle.')
        self.graph.add_edge('Node_202', 'Node_204', label='yes')
        self.graph.add_edge('Node_204', 'Node_205', label='Node_204_205')
        self.graph.add_node('Node_205', type=['speak', 'show'], text='#deslicen suavemente la rueda en el eje.# Be very careful!. #¡Tengan cuidado!# One of you can hold the axle, while the other pushes the wheel. #Trabajen juntos! Uno puede sostener el eje, el otro empuja la rueda.# Be very careful!', image='../Assets/Bilingual_Lego/ferris_step_23.png', pause={'after': 10})
        self.graph.add_edge('Node_205', 'Node_206', label='Node_205_206')
        self.graph.add_node('Node_206', type=['speak'], text='Now, let`s test it!  If it spins nicely, raise your card. #Ahora, vamos a probarlo! Si gira bien, levanten sus tarjetas.#')
        self.graph.add_edge('Node_206', 'Node_207', label='Node_206_207')
        self.graph.add_node('Node_207', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_208', type=['speak'], text='What can be the problem? #¿Cuál puede ser el problema?# Who can help the wheel turn around?.')
        self.graph.add_edge('Node_207', 'Node_208', label='no')
        self.graph.add_edge('Node_208', 'Node_207', label='Node_208_207')
        self.graph.add_node('Node_209', type=['speak'], text='You did it!')
        self.graph.add_edge('Node_207', 'Node_209', label='yes')
        self.graph.add_edge('Node_209', 'Node_211', label='Node_209_211')
        self.graph.add_node('Node_210', type=['speak'], text='#¡Excelente!#')
        self.graph.add_edge('Node_207', 'Node_210', label='timeout')
        self.graph.add_edge('Node_210', 'Node_211', label='Node_210_211')
        self.graph.add_node('Node_211', type=['audio', 'move'], audio='laugh.wav', motors='arms_up')
        self.graph.add_edge('Node_211', 'Node_212', label='Node_211_212')
        self.graph.add_node('Node_212', type=['speak'], text='Our Ferris Wheel is standing tall and spinning around! #Muy bien! ¡Nuestra rueda de la fortuna está de pie y girando!#')
        self.graph.add_edge('Node_212', 'Node_213', label='Node_212_213')
        self.graph.add_node('Node_213', type=['speak'], text='You built it together.', pause={'after': 1})
        self.graph.add_edge('Node_213', 'Node_214', label='Node_213_214')
        self.graph.add_node('Node_214', type=['speak', 'move'], text='High five your friend and give a big smile!', motors='clap')
        self.graph.add_edge('Node_214', 'Node_215', label='Node_214_215')


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Run Monolingual_Ferris script.')
    parser.add_argument('--offset', type=str, help='Offset from a specific node')
    args = parser.parse_args()
    if not args.offset:
        start_node = 'start'
    else:
        start_node = f"Node_{args.offset}"
    sg = Bilingual_Lego()
    sg.init_graph()

    fuzzy = Character(child=False, gender='female', activity='Bilingual_Lego', languages=['en', 'es'])
    script = Script(graph=sg, character=fuzzy)
    script.generateAllSpeech()
    script.check_assets()
    script.run(start_node=start_node)

