import sys
sys.path.append('../Character')
import json
import sys
from character import Character
from script import *
from scriptGraph import ScriptGraph
from characterDefinitions import CHARACTER_FOLDER

# Auto-generated file
# Name: Monolingual_Ferris
# Character: female Child
activity_name = 'Monolingual_Ferris'
class Monolingual_Ferris(ScriptGraph) :
    def __init__(self):
        super().__init__()

    def init_graph(self):


        self.graph.add_node('start', type=['character'])
        self.graph.add_edge('start', 'Node_2', label='start_2')
        self.graph.add_node('Node_2', type=['speak', 'move'], text='Hello friends! I`m Gigi the robot!', motors='wave_hello')
        self.graph.add_edge('Node_2', 'Node_3', label='Node_2_3')
        self.graph.add_node('Node_3', type=['speak'], text='I love building with LEGO and playing with my friends.  I also love learning new things and helping my friends learn, too! What do you like to do with your friends?', pause={'after': 10})
        self.graph.add_edge('Node_3', 'Node_4', label='Node_3_4')
        self.graph.add_node('Node_4', type=['speak'], text='That`s great! We will have a lot of fun together!')
        self.graph.add_edge('Node_4', 'Node_5', label='Node_4_5')
        self.graph.add_node('Node_5', type=['speak'], text='Let`s say ‘hello`! Let`s all waive our hands and say it together! #hello!#', pause={'after': 3})
        self.graph.add_edge('Node_5', 'Node_6', label='Node_5_6')
        self.graph.add_node('Node_6', type=['speak', 'face', 'move'], text='If you want to play, raise your hands!', face=basic_sequences['look_up'], motors='arms_up', pause={'after': 1})
        self.graph.add_edge('Node_6', 'Node_7', label='Node_6_7')
        self.graph.add_node('Node_7', type=['speak'], text='High!', pause={'after': 1})
        self.graph.add_edge('Node_7', 'Node_8', label='Node_7_8')
        self.graph.add_node('Node_8', type=['speak'], text='Higher!', pause={'after': 1})
        self.graph.add_edge('Node_8', 'Node_9', label='Node_8_9')
        self.graph.add_node('Node_9', type=['speak'], text='This is great! I`m so happy you want to play with me.')
        self.graph.add_edge('Node_9', 'Node_10', label='Node_9_10')
        self.graph.add_node('Node_10', type=['speak', 'move'], text='Can you see? You have a bin with LEGO blocks and LEGO figures on the table.', motors='arms_down', pause={'after': 3})
        self.graph.add_edge('Node_10', 'Node_11', label='Node_10_11')
        self.graph.add_node('Node_11', type=['speak'], text='Can you find a LEGO figure that you like? Everyone can choose one LEGO figure and decorate it.')
        self.graph.add_edge('Node_11', 'Node_12', label='Node_11_12')
        self.graph.add_node('Node_12', type=['speak'], text='Show your figure to your friends. When you are done, raise the black and white card you have in front of you.')
        self.graph.add_edge('Node_12', 'Node_13', label='Node_12_13')
        self.graph.add_node('Node_13', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_14', type=['speak'], text='I see you are having fun. Let me know when you are done by raising the card.')
        self.graph.add_edge('Node_13', 'Node_14', label='no')
        self.graph.add_edge('Node_14', 'Node_13', label='Node_14_13')
        self.graph.add_node('Node_15', type=['speak'], text='Did you pick a boy or a girl? What kind of hair do they have? Curly? Straight? Short? Long? What color is their shirt?')
        self.graph.add_edge('Node_13', 'Node_15', label='yes')
        self.graph.add_edge('Node_15', 'Node_16', label='Node_15_16')
        self.graph.add_node('Node_16', type=['speak', 'move'], text='Show your friends your figure and tell them what you picked.', motors='look_from_side_to_side', pause={'after': 10})
        self.graph.add_edge('Node_16', 'Node_17', label='Node_16_17')
        self.graph.add_node('Node_17', type=['speak', 'move'], text='Does your figure have a name? Share it with your friends! .', motors='look_from_side_to_side', pause={'after': 10})
        self.graph.add_edge('Node_17', 'Node_18', label='Node_17_18')
        self.graph.add_node('Node_18', type=['speak'], text='Now, we`re ready to start!')
        self.graph.add_edge('Node_18', 'Node_19', label='Node_18_19')
        self.graph.add_node('Node_19', type=['speak'], text='Today we`re going to build a Ferris wheel. Do you know what a Ferris wheel is?')
        self.graph.add_edge('Node_19', 'Node_20', label='Node_19_20')
        self.graph.add_node('Node_20', type=['hear'], words='["yes", "no", "[unk]"]')
        self.graph.add_node('Node_21', type=['speak'], text='Ferris wheels are so much fun! I love going on them and spinning round and round.')
        self.graph.add_edge('Node_20', 'Node_21', label='yes')
        self.graph.add_edge('Node_21', 'Node_22', label='Node_21_22')
        self.graph.add_node('Node_22', type=['speak'], text='Who can tell us? What is a Ferris wheel?', pause={'after': 5})
        self.graph.add_edge('Node_20', 'Node_22', label='no')
        self.graph.add_edge('Node_22', 'Node_23', label='Node_22_23')
        self.graph.add_node('Node_23', type=['speak'], text='Yes! A Ferris wheel is a big wheel that spins round and round. You can find Ferris wheels in carnivals! I love them!')
        self.graph.add_edge('Node_23', 'Node_24', label='Node_23_24')
        self.graph.add_node('Node_24', type=['audio'], audio='laugh.wav')
        self.graph.add_edge('Node_24', 'Node_25', label='Node_24_25')
        self.graph.add_node('Node_25', type=['speak'], text='Have you ever been on a Ferris wheel? Tell your friends.', pause={'after': 10})
        self.graph.add_edge('Node_25', 'Node_26', label='Node_25_26')
        self.graph.add_node('Node_26', type=['speak'], text='Today we will build a big Ferris wheel together for our LEGO friends!')
        self.graph.add_edge('Node_26', 'Node_27', label='Node_26_27')
        self.graph.add_node('Node_27', type=['speak'], text='We can build together! Everyone will have an important role!')
        self.graph.add_edge('Node_27', 'Node_28', label='Node_27_28')
        self.graph.add_node('Node_28', type=['speak', 'face', 'move'], text='Look at the bin at the center of your table! It has all the pieces we need to build a Ferris wheel. So Let`s get started!', face=basic_sequences['look_down'], motors='arms_down')
        self.graph.add_edge('Node_28', 'Node_29', label='Node_28_29')
        self.graph.add_node('Node_29', type=['speak'], text='Are you ready?', pause={'after': 5})
        self.graph.add_edge('Node_29', 'Node_30', label='Node_29_30')
        self.graph.add_node('Node_30', type=['speak'], text='Are you ready?')
        self.graph.add_edge('Node_30', 'Node_31', label='Node_30_31')
        self.graph.add_node('Node_31', type=['hear'], words='["yes", "[unk]"]')
        self.graph.add_node('Node_32', type=['speak'], text='Great!')
        self.graph.add_edge('Node_31', 'Node_32', label='yes')
        self.graph.add_edge('Node_32', 'Node_33', label='Node_32_33')
        self.graph.add_node('Node_33', type=['speak'], text='Excellent!')
        self.graph.add_edge('Node_31', 'Node_33', label='yes')
        self.graph.add_edge('Node_33', 'Node_34', label='Node_33_34')
        self.graph.add_node('Node_34', type=['speak', 'show'], text='Who wants to be the finder in this step? Can you find the yellow controller block and four green pins?', image='../Assets/Monolingual_Ferris/ferris_step_01.png')
        self.graph.add_edge('Node_34', 'Node_35', label='Node_34_35')
        self.graph.add_node('Node_35', type=['speak', 'show'], text='When you are done, raise your card.', image='../Assets/Monolingual_Ferris/ferris_step_01.png')
        self.graph.add_edge('Node_35', 'Node_36', label='Node_35_36')
        self.graph.add_node('Node_36', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_37', type=['speak'], text='Still searching? You can all look for this part together.')
        self.graph.add_edge('Node_36', 'Node_37', label='no')
        self.graph.add_edge('Node_37', 'Node_36', label='Node_37_36')
        self.graph.add_node('Node_38', type=['speak'], text='Great! That`s our yellow controller!')
        self.graph.add_edge('Node_36', 'Node_38', label='yes')
        self.graph.add_edge('Node_38', 'Node_39', label='Node_38_39')
        self.graph.add_node('Node_39', type=['speak'], text='Now, we need a builder for this step. Who will it be? Remember, we will switch roles so everyone gets a chance to play all the roles!')
        self.graph.add_edge('Node_39', 'Node_40', label='Node_39_40')
        self.graph.add_node('Node_40', type=['speak', 'show'], text='Now, connect the controller to the gray rectangular LEGO plate, the base.', image='../Assets/Monolingual_Ferris/ferris_step_02.png')
        self.graph.add_edge('Node_40', 'Node_41', label='Node_40_41')
        self.graph.add_node('Node_41', type=['speak'], text='Now we need an assistant. Who can hold the base while the builder clicks the controller in?')
        self.graph.add_edge('Node_41', 'Node_42', label='Node_41_42')
        self.graph.add_node('Node_42', type=['speak', 'show'], text='Raise your cards when you are ready.', image='../Assets/Monolingual_Ferris/ferris_step_02.png')
        self.graph.add_edge('Node_42', 'Node_43', label='Node_42_43')
        self.graph.add_node('Node_43', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_44', type=['speak', 'show'], text='Not quite done? I will wait.', image='../Assets/Monolingual_Ferris/ferris_step_02.png')
        self.graph.add_edge('Node_43', 'Node_44', label='no')
        self.graph.add_edge('Node_44', 'Node_43', label='Node_44_43')
        self.graph.add_node('Node_45', type=['speak'], text='Finally, we need a checker. Is what you built the same as in this picture?')
        self.graph.add_edge('Node_45', 'Node_46', label='Node_45_46')
        self.graph.add_node('Node_46', type=['speak'], text='Excellent teamwork! Isn`t it great to work together?')
        self.graph.add_edge('Node_43', 'Node_46', label='yes')
        self.graph.add_edge('Node_46', 'Node_47', label='Node_46_47')
        self.graph.add_node('Node_47', type=['speak'], text='This tower is very important. It is 3 blocks high!')
        self.graph.add_edge('Node_47', 'Node_48', label='Node_47_48')
        self.graph.add_node('Node_48', type=['speak'], text='Let`s count to three!', pause={'after': 5})
        self.graph.add_edge('Node_48', 'Node_49', label='Node_48_49')
        self.graph.add_node('Node_49', type=['hear'], words='["One", "two", "three", "[unk]"]')
        self.graph.add_node('Node_50', type=['speak'], text='One, two, three.')
        self.graph.add_edge('Node_49', 'Node_50', label='one')
        self.graph.add_edge('Node_50', 'Node_51', label='Node_50_51')
        self.graph.add_node('Node_51', type=['speak'], text='One, two, three.')
        self.graph.add_edge('Node_49', 'Node_51', label='two')
        self.graph.add_edge('Node_51', 'Node_52', label='Node_51_52')
        self.graph.add_node('Node_52', type=['speak'], text='One, two, three.')
        self.graph.add_edge('Node_49', 'Node_52', label='three')
        self.graph.add_edge('Node_52', 'Node_53', label='Node_52_53')
        self.graph.add_node('Node_53', type=['speak', 'show'], text='Who will be the builder now? , stack three bricks to build a tower. First put the yellow part on the gray base.', image='../Assets/Monolingual_Ferris/ferris_step_03.png')
        self.graph.add_edge('Node_53', 'Node_54', label='Node_53_54')
        self.graph.add_node('Node_54', type=['speak', 'show'], text='Then stack one red brick as base and three bricks, one on top of the other.', image='../Assets/Monolingual_Ferris/ferris_step_05.png')
        self.graph.add_edge('Node_54', 'Node_55', label='Node_54_55')
        self.graph.add_node('Node_55', type=['speak'], text='Let`s take turns! Who wants to build now?! Stack the blocks, one on top of the other?  Who wants to count them?')
        self.graph.add_edge('Node_55', 'Node_56', label='Node_55_56')
        self.graph.add_node('Node_56', type=['speak', 'show'], text='When it`s done, raise your card.', image='../Assets/Monolingual_Ferris/ferris_step_05.png')
        self.graph.add_edge('Node_56', 'Node_57', label='Node_56_57')
        self.graph.add_node('Node_57', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_58', type=['speak', 'show'], text='Not quite done? I will wait.', image='../Assets/Monolingual_Ferris/ferris_step_05.png')
        self.graph.add_edge('Node_57', 'Node_58', label='no')
        self.graph.add_edge('Node_58', 'Node_57', label='Node_58_57')
        self.graph.add_node('Node_59', type=['speak'], text='Excellent teamwork!')
        self.graph.add_edge('Node_57', 'Node_59', label='yes')
        self.graph.add_edge('Node_59', 'Node_60', label='Node_59_60')
        self.graph.add_node('Node_60', type=['speak'], text='Time to add the second tower!')
        self.graph.add_edge('Node_60', 'Node_61', label='Node_60_61')
        self.graph.add_node('Node_61', type=['speak'], text='What parts do we need to build the tower? Who wants to be the finder?', pause={'after': 3})
        self.graph.add_edge('Node_61', 'Node_62', label='Node_61_62')
        self.graph.add_node('Node_62', type=['speak'], text='Great! Find the yellow tower, the yellow plate and these two orange  pieces. Raise your card when you`re done!')
        self.graph.add_edge('Node_62', 'Node_63', label='Node_62_63')
        self.graph.add_node('Node_63', type=['speak'], text='Are we ready to build? Who will be the builder this time?', pause={'after': 3})
        self.graph.add_edge('Node_63', 'Node_64', label='Node_63_64')
        self.graph.add_node('Node_64', type=['speak', 'show'], text='Put the tower together! The builder can hold the baseplate while the assistant presses the tower down.', image='../Assets/Monolingual_Ferris/ferris_step_08.png')
        self.graph.add_edge('Node_64', 'Node_65', label='Node_64_65')
        self.graph.add_node('Node_65', type=['speak'], text='Let`s check and see: does the tower look right? Is it the same as in the picture?')
        self.graph.add_edge('Node_65', 'Node_66', label='Node_65_66')
        self.graph.add_node('Node_66', type=['speak'], text='Let`s see: the yellow part goes first, and then the two small orange parts go on top of it.')
        self.graph.add_edge('Node_66', 'Node_67', label='Node_66_67')
        self.graph.add_node('Node_67', type=['speak'], text='Everybody can check and help!')
        self.graph.add_edge('Node_67', 'Node_68', label='Node_67_68')
        self.graph.add_node('Node_68', type=['speak', 'show'], text='Raise your cards when the tower is ready! on top of it and two small orange pieces on top of that. One friend can hold the baseplate while the other presses the tower down.', image='../Assets/Monolingual_Ferris/ferris_step_08.png')
        self.graph.add_edge('Node_68', 'Node_69', label='Node_68_69')
        self.graph.add_node('Node_69', type=['speak', 'show'], text='If it is connected, raise your cards.', image='../Assets/Monolingual_Ferris/ferris_step_08.png')
        self.graph.add_edge('Node_69', 'Node_70', label='Node_69_70')
        self.graph.add_node('Node_70', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_71', type=['speak', 'show'], text='Still building? I will wait.', image='../Assets/Monolingual_Ferris/ferris_step_08.png')
        self.graph.add_edge('Node_70', 'Node_71', label='no')
        self.graph.add_edge('Node_71', 'Node_70', label='Node_71_70')
        self.graph.add_node('Node_72', type=['speak'], text='The second tower is ready! Great job.')
        self.graph.add_edge('Node_70', 'Node_72', label='yes')
        self.graph.add_edge('Node_72', 'Node_73', label='Node_72_73')
        self.graph.add_node('Node_73', type=['speak'], text='Who wants to be the finder now? What pieces do we need to build the light? Take a look!')
        self.graph.add_edge('Node_73', 'Node_74', label='Node_73_74')
        self.graph.add_node('Node_74', type=['speak'], text='Do we have everything we need?')
        self.graph.add_edge('Node_74', 'Node_75', label='Node_74_75')
        self.graph.add_node('Node_75', type=['speak'], text='Now, whose turn is it to be the builder? Attach the parts and put the light together!')
        self.graph.add_edge('Node_75', 'Node_76', label='Node_75_76')
        self.graph.add_node('Node_76', type=['speak'], text='Go ahead, build the light!')
        self.graph.add_edge('Node_76', 'Node_77', label='Node_76_77')
        self.graph.add_node('Node_77', type=['speak'], text='Attach the parts and put the light together!')
        self.graph.add_edge('Node_77', 'Node_78', label='Node_77_78')
        self.graph.add_node('Node_78', type=['speak', 'show'], text='Find the light piece and connect the green pieces to it, similar to the motor.', image='../Assets/Monolingual_Ferris/ferris_step_09.png', pause={'after': 5})
        self.graph.add_edge('Node_78', 'Node_79', label='Node_78_79')
        self.graph.add_node('Node_79', type=['speak'], text='Time to check! Does the light look like in the picture? Raise your cards if you think it`s correct.')
        self.graph.add_edge('Node_79', 'Node_80', label='Node_79_80')
        self.graph.add_node('Node_80', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_81', type=['speak'], text='oh uh! Let`s check again! Is there a mistake? Who can help fix it?')
        self.graph.add_edge('Node_80', 'Node_81', label='no')
        self.graph.add_edge('Node_81', 'Node_82', label='Node_81_82')
        self.graph.add_node('Node_82', type=['speak'], text='All the cards are raised] Good work! It`s so important to check our work at each step so we can catch our mistakes on time!')
        self.graph.add_edge('Node_80', 'Node_82', label='yes')
        self.graph.add_edge('Node_82', 'Node_83', label='Node_82_83')
        self.graph.add_node('Node_83', type=['speak'], text='Is the light attached to the base? Like in this picture?')
        self.graph.add_edge('Node_83', 'Node_84', label='Node_83_84')
        self.graph.add_node('Node_84', type=['speak'], text='If it isn`t, let`s attach it now! Builder, go ahead!')
        self.graph.add_edge('Node_84', 'Node_85', label='Node_84_85')
        self.graph.add_node('Node_85', type=['speak', 'show'], text='When the light is attached to the base, hold up your cards.', image='../Assets/Monolingual_Ferris/ferris_step_10.png')
        self.graph.add_edge('Node_85', 'Node_86', label='Node_85_86')
        self.graph.add_node('Node_86', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_87', type=['speak', 'show'], text='Take your time. I will wait here until the light piece is attached.', image='../Assets/Monolingual_Ferris/ferris_step_10.png')
        self.graph.add_edge('Node_86', 'Node_87', label='no')
        self.graph.add_edge('Node_87', 'Node_86', label='Node_87_86')
        self.graph.add_node('Node_88', type=['speak'], text='That was great teamwork!')
        self.graph.add_edge('Node_86', 'Node_88', label='yes')
        self.graph.add_edge('Node_88', 'Node_89', label='Node_88_89')
        self.graph.add_node('Node_89', type=['speak'], text='Now let`s find the motor and attach the green pins to it!  Who wants to be the finder now? Raise your card!', pause={'after': 3})
        self.graph.add_edge('Node_89', 'Node_90', label='Node_89_90')
        self.graph.add_node('Node_90', type=['speak'], text='Oh! Two friends want to be finders. I love it when we collaborate! You can work together to find all the pieces we need to build the motor!')
        self.graph.add_edge('Node_90', 'Node_91', label='Node_90_91')
        self.graph.add_node('Node_91', type=['speak', 'show'], text='Great! find the motor, attach green pins to it.', image='../Assets/Monolingual_Ferris/ferris_step_11.png', pause={'after': 5})
        self.graph.add_edge('Node_91', 'Node_92', label='Node_91_92')
        self.graph.add_node('Node_92', type=['speak'], text='Now, who wants to attach the motor to the tower?', pause={'after': 3})
        self.graph.add_edge('Node_92', 'Node_93', label='Node_92_93')
        self.graph.add_node('Node_93', type=['speak'], text='Make sure it is attached in the correct spot!')
        self.graph.add_edge('Node_93', 'Node_94', label='Node_93_94')
        self.graph.add_node('Node_94', type=['speak', 'show'], text='Let`s check together! If you think the motor is attached the right way, raise your cards!', image='../Assets/Monolingual_Ferris/ferris_step_12.png', pause={'after': 5})
        self.graph.add_edge('Node_94', 'Node_95', label='Node_94_95')
        self.graph.add_node('Node_95', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_96', type=['speak', 'show'], text='Let me know when it is attached. I will wait!', image='../Assets/Monolingual_Ferris/ferris_step_12.png')
        self.graph.add_edge('Node_95', 'Node_96', label='no')
        self.graph.add_edge('Node_96', 'Node_95', label='Node_96_95')
        self.graph.add_node('Node_97', type=['speak'], text='That was great teamwork!')
        self.graph.add_edge('Node_95', 'Node_97', label='yes')
        self.graph.add_edge('Node_97', 'Node_98', label='Node_97_98')
        self.graph.add_node('Node_98', type=['speak'], text='The wheel is really coming together! Now, your figures need a way to reach  the ferris wheel. Who has an idea? Tell your friends!!', pause={'after': 5})
        self.graph.add_edge('Node_98', 'Node_99', label='Node_98_99')
        self.graph.add_node('Node_99', type=['speak'], text='How about building stairs?')
        self.graph.add_edge('Node_99', 'Node_100', label='Node_99_100')
        self.graph.add_node('Node_100', type=['speak'], text='Who`s turn is it to be the finder? Find the yellow brick and the blue tiles in the picture! Raise your card when you`re done!', pause={'after': 5})
        self.graph.add_edge('Node_100', 'Node_101', label='Node_100_101')
        self.graph.add_node('Node_101', type=['speak', 'show'], text='Now, let`s build the stairs! Who`s turn is it to be the builder?  connect the yellow brick and the blue tiles.', image='../Assets/Monolingual_Ferris/ferris_step_13.png', pause={'after': 5})
        self.graph.add_edge('Node_101', 'Node_102', label='Node_101_102')
        self.graph.add_node('Node_102', type=['speak'], text='Then connect two more blue tiles.')
        self.graph.add_edge('Node_102', 'Node_103', label='Node_102_103')
        self.graph.add_node('Node_103', type=['speak', 'show'], text='When they`re all connected, raise your card.', image='../Assets/Monolingual_Ferris/ferris_step_14.png')
        self.graph.add_edge('Node_103', 'Node_104', label='Node_103_104')
        self.graph.add_node('Node_104', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_105', type=['speak', 'show'], text='Still fixing the stairs? I will wait until you are done.', image='../Assets/Monolingual_Ferris/ferris_step_14.png')
        self.graph.add_edge('Node_104', 'Node_105', label='no')
        self.graph.add_edge('Node_105', 'Node_104', label='Node_105_104')
        self.graph.add_node('Node_106', type=['speak'], text='The blue stairs are ready!  What a super team!')
        self.graph.add_edge('Node_104', 'Node_106', label='yes')
        self.graph.add_edge('Node_106', 'Node_107', label='Node_106_107')
        self.graph.add_node('Node_107', type=['speak'], text='I love the color blue. Do you like blue too?', pause={'after': 5})
        self.graph.add_edge('Node_107', 'Node_108', label='Node_107_108')
        self.graph.add_node('Node_108', type=['hear'], words='["yes", "no", "[unk]"]')
        self.graph.add_node('Node_109', type=['speak'], text='It`s my favorite color!')
        self.graph.add_edge('Node_108', 'Node_109', label='yes')
        self.graph.add_edge('Node_109', 'Node_110', label='Node_109_110')
        self.graph.add_node('Node_110', type=['speak'], text='That`s okay. What color do you like best?')
        self.graph.add_edge('Node_108', 'Node_110', label='no')
        self.graph.add_edge('Node_110', 'Node_111', label='Node_110_111')
        self.graph.add_node('Node_111', type=['hear'], words='["yellow", "red", "green", "gray", "black", "white", "pink", "purple", "brown", "[unk]"]')
        self.graph.add_node('Node_112', type=['speak'], text='I like those too!')
        self.graph.add_edge('Node_111', 'Node_112', label='yellow')
        self.graph.add_edge('Node_112', 'Node_113', label='Node_112_113')
        self.graph.add_node('Node_113', type=['speak'], text='I like those too!')
        self.graph.add_edge('Node_111', 'Node_113', label='red')
        self.graph.add_edge('Node_113', 'Node_114', label='Node_113_114')
        self.graph.add_node('Node_114', type=['speak'], text='I like those too!')
        self.graph.add_edge('Node_111', 'Node_114', label='green')
        self.graph.add_edge('Node_114', 'Node_115', label='Node_114_115')
        self.graph.add_node('Node_115', type=['speak'], text='I like those too!')
        self.graph.add_edge('Node_111', 'Node_115', label='gray')
        self.graph.add_edge('Node_115', 'Node_116', label='Node_115_116')
        self.graph.add_node('Node_116', type=['speak'], text='I like those too!')
        self.graph.add_edge('Node_111', 'Node_116', label='black')
        self.graph.add_edge('Node_116', 'Node_117', label='Node_116_117')
        self.graph.add_node('Node_117', type=['speak'], text='I like those too!')
        self.graph.add_edge('Node_111', 'Node_117', label='white')
        self.graph.add_edge('Node_117', 'Node_118', label='Node_117_118')
        self.graph.add_node('Node_118', type=['speak'], text='I like those too!')
        self.graph.add_edge('Node_111', 'Node_118', label='pink')
        self.graph.add_edge('Node_118', 'Node_119', label='Node_118_119')
        self.graph.add_node('Node_119', type=['speak'], text='I like those too!')
        self.graph.add_edge('Node_111', 'Node_119', label='purple')
        self.graph.add_edge('Node_119', 'Node_120', label='Node_119_120')
        self.graph.add_node('Node_120', type=['speak'], text='I like those too!')
        self.graph.add_edge('Node_111', 'Node_120', label='brown')
        self.graph.add_edge('Node_120', 'Node_121', label='Node_120_121')
        self.graph.add_node('Node_121', type=['speak', 'show'], text='Okay, now, find the rod and put it in the motor. That will make the ferris wheel turn.', image='../Assets/Monolingual_Ferris/ferris_step_15.png', pause={'after': 15})
        self.graph.add_edge('Node_121', 'Node_122', label='Node_121_122')
        self.graph.add_node('Node_122', type=['speak'], text='Can you make your hands spin like a wheel?', pause={'after': 5})
        self.graph.add_edge('Node_122', 'Node_123', label='Node_122_123')
        self.graph.add_node('Node_123', type=['speak'], text='Have you found the rod? Raise your cards.', pause={'after': 5})
        self.graph.add_edge('Node_123', 'Node_124', label='Node_123_124')
        self.graph.add_node('Node_124', type=['speak', 'show'], text='Who wants to attach the rod to the motor? Look at this picture to see how to attach it.', image='../Assets/Monolingual_Ferris/ferris_step_15.png', pause={'after': 15})
        self.graph.add_edge('Node_124', 'Node_125', label='Node_124_125')
        self.graph.add_node('Node_125', type=['speak'], text='Great!')
        self.graph.add_edge('Node_125', 'Node_126', label='Node_125_126')
        self.graph.add_node('Node_126', type=['speak', 'show'], text='Now we build the arms of the ferris wheel. First, start with the main structure.', image='../Assets/Monolingual_Ferris/ferris_step_16.png', pause={'after': 15})
        self.graph.add_edge('Node_126', 'Node_127', label='Node_126_127')
        self.graph.add_node('Node_127', type=['speak', 'show'], text='Now, connect the green pieces to the round wheel center to form an X. Holder, you can hold the wheel while your friend is adding the arms.', image='../Assets/Monolingual_Ferris/ferris_step_17.png')
        self.graph.add_edge('Node_127', 'Node_128', label='Node_127_128')
        self.graph.add_node('Node_128', type=['speak', 'show'], text='When they`re all connected, raise your card.', image='../Assets/Monolingual_Ferris/ferris_step_17.png')
        self.graph.add_edge('Node_128', 'Node_129', label='Node_128_129')
        self.graph.add_node('Node_129', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_130', type=['speak', 'show'], text='need more time?  I will wait until you are done.', image='../Assets/Monolingual_Ferris/ferris_step_17.png')
        self.graph.add_edge('Node_129', 'Node_130', label='no')
        self.graph.add_edge('Node_130', 'Node_129', label='Node_130_129')
        self.graph.add_node('Node_131', type=['speak'], text='We have an X! ! What a super team!')
        self.graph.add_edge('Node_129', 'Node_131', label='yes')
        self.graph.add_edge('Node_131', 'Node_132', label='Node_131_132')
        self.graph.add_node('Node_132', type=['speak'], text='Now let`s complete the ferris wheel!')
        self.graph.add_edge('Node_132', 'Node_133', label='Node_132_133')
        self.graph.add_node('Node_133', type=['speak'], text='Let`s look at the instructions together? What is the part we need for this step? Everyone can look together now! Choose who builds this step! Builder, raise your card when you`re done!')
        self.graph.add_edge('Node_133', 'Node_134', label='Node_133_134')
        self.graph.add_node('Node_134', type=['speak', 'show'], text='Put one more purple circle.', image='../Assets/Monolingual_Ferris/ferris_step_18.png', pause={'after': 10})
        self.graph.add_edge('Node_134', 'Node_135', label='Node_134_135')
        self.graph.add_node('Node_135', type=['speak', 'show'], text='Then four white pieces . Work together.', image='../Assets/Monolingual_Ferris/ferris_step_19.png', pause={'after': 10})
        self.graph.add_edge('Node_135', 'Node_136', label='Node_135_136')
        self.graph.add_node('Node_136', type=['speak', 'show'], text='Then a green round piece.', image='../Assets/Monolingual_Ferris/ferris_step_20.png', pause={'after': 5})
        self.graph.add_edge('Node_136', 'Node_137', label='Node_136_137')
        self.graph.add_node('Node_137', type=['speak', 'show'], text='And an orange cone.', image='../Assets/Monolingual_Ferris/ferris_step_21.png', pause={'after': 10})
        self.graph.add_edge('Node_137', 'Node_138', label='Node_137_138')
        self.graph.add_node('Node_138', type=['speak'], text='Our wheel is done! Now let`s build nice seats so your figures can enjoy the ride!... You need to build four seats, one for each arm of the wheel, and for each LEGO figure! Let`s work together! Each friend can pick a seat to build! Help each other!')
        self.graph.add_edge('Node_138', 'Node_139', label='Node_138_139')
        self.graph.add_node('Node_139', type=['speak', 'show'], text='Let me know when you are done.', image='../Assets/Monolingual_Ferris/ferris_step_22.png')
        self.graph.add_edge('Node_139', 'Node_140', label='Node_139_140')
        self.graph.add_node('Node_140', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_141', type=['speak', 'show'], text='Still finalizing those seats? I will wait until you are done.', image='../Assets/Monolingual_Ferris/ferris_step_22.png')
        self.graph.add_edge('Node_140', 'Node_141', label='no')
        self.graph.add_edge('Node_141', 'Node_140', label='Node_141_140')
        self.graph.add_node('Node_142', type=['speak'], text='You have the wheel! What a great team!')
        self.graph.add_edge('Node_140', 'Node_142', label='yes')
        self.graph.add_edge('Node_142', 'Node_143', label='Node_142_143')
        self.graph.add_node('Node_143', type=['speak', 'show'], text='Finally, we are ready to put the wheel on the axle. Who will be the builder now?  And who can be the holder? Gently slide the wheel onto the axle. Be very careful!. One of you can hold the axle, while the other pushes the wheel.', image='../Assets/Monolingual_Ferris/ferris_step_23.png', pause={'after': 10})
        self.graph.add_edge('Node_143', 'Node_144', label='Node_143_144')
        self.graph.add_node('Node_144', type=['speak'], text='Now, Lets test it!  If it spins nicely, raise your card.')
        self.graph.add_edge('Node_144', 'Node_145', label='Node_144_145')
        self.graph.add_node('Node_145', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_146', type=['speak'], text='What can be the problem? Who can help the wheel turn around?.')
        self.graph.add_edge('Node_145', 'Node_146', label='no')
        self.graph.add_edge('Node_146', 'Node_145', label='Node_146_145')
        self.graph.add_node('Node_147', type=['speak', 'move'], text='You did it! Our Ferris Wheel is standing tall and spinning around! You built it together. high five your friend and give a big smile!', motors='clap')
        self.graph.add_edge('Node_145', 'Node_147', label='yes')
        self.graph.add_edge('Node_147', 'Node_148', label='Node_147_148')


if __name__ == "__main__":
    sg = Monolingual_Ferris()
    sg.init_graph()

    fuzzy = Character(child=True, gender='female', activity='Monolingual_Ferris', languages=['en'])
    script = Script(graph=sg, character=fuzzy)
    script.generateAllSpeech()
    script.check_assets()
    script.run()

