import sys
sys.path.append('../Character')
import json
import sys
from character import Character
from script import *
from scriptGraph import ScriptGraph
from characterDefinitions import CHARACTER_FOLDER

# Auto-generated file
# Name: Monolingual_Ferris
# Character: female Child
activity_name = 'Monolingual_Ferris'
class Monolingual_Ferris(ScriptGraph) :
    def __init__(self):
        super().__init__()

    def init_graph(self):


        self.graph.add_node('start', type=['character'])
        self.graph.add_edge('start', 'Node_2', label='start_2')
        self.graph.add_node('Node_2', type=['speak', 'move'], text='Hello friends! I`m Gigi the robot!', motors='wave_hello')
        self.graph.add_edge('Node_2', 'Node_3', label='Node_2_3')
        self.graph.add_node('Node_3', type=['speak'], text='I love building with LEGO and playing with my friends.')
        self.graph.add_edge('Node_3', 'Node_4', label='Node_3_4')
        self.graph.add_node('Node_4', type=['speak', 'face: look_up, move: hands_up'], text='Would you like to play with me?')
        self.graph.add_edge('Node_4', 'Node_5', label='Node_4_5')
        self.graph.add_node('Node_5', type=['speak', 'move'], text='If you want to play, raise your hands!', motors='arms_up', pause={'after': 2})
        self.graph.add_edge('Node_5', 'Node_6', label='Node_5_6')
        self.graph.add_node('Node_6', type=['speak'], text='High… higher… This is great! I`m so happy you want to play with me.')
        self.graph.add_edge('Node_6', 'Node_7', label='Node_6_7')
        self.graph.add_node('Node_7', type=['speak', 'move'], text='Oh, but wait! Lets say hello first!', motors='look_from_side_to_side')
        self.graph.add_edge('Node_7', 'Node_8', label='Node_7_8')
        self.graph.add_node('Node_8', type=['speak', 'move'], text='Can you see? You have a bin with LEGO blocks and figures on the table.', motors='arms_down')
        self.graph.add_edge('Node_8', 'Node_9', label='Node_8_9')
        self.graph.add_node('Node_9', type=['speak'], text='Can you find a LEGO figure that you like? Everyone can choose one LEGO figure and decorate it.')
        self.graph.add_edge('Node_9', 'Node_10', label='Node_9_10')
        self.graph.add_node('Node_10', type=['speak'], text='When you are done, raise the smiley card you have in front of you.')
        self.graph.add_edge('Node_10', 'Node_11', label='Node_10_11')
        self.graph.add_node('Node_11', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_12', type=['speak'], text='I see you are having fun. Let me know when you are done by raising the smiley card.')
        self.graph.add_edge('Node_11', 'Node_12', label='no')
        self.graph.add_edge('Node_12', 'Node_11', label='Node_12_11')
        self.graph.add_node('Node_13', type=['speak'], text='Did you pick a boy or a girl? What kind of hair do they have? Curly? Straight? Short? Long? What color is their shirt?')
        self.graph.add_edge('Node_11', 'Node_13', label='yes')
        self.graph.add_edge('Node_13', 'Node_14', label='Node_13_14')
        self.graph.add_node('Node_14', type=['speak', 'move'], text='Show your friends your figure and tell them what you picked.', motors='look_from_side_to_side', pause={'after': 10})
        self.graph.add_edge('Node_14', 'Node_15', label='Node_14_15')
        self.graph.add_node('Node_15', type=['speak'], text='Now, we`re ready to start!')
        self.graph.add_edge('Node_15', 'Node_16', label='Node_15_16')
        self.graph.add_node('Node_16', type=['speak'], text='Today we`re going to build a Ferris wheel. Do you know what a Ferris wheel is?')
        self.graph.add_edge('Node_16', 'Node_17', label='Node_16_17')
        self.graph.add_node('Node_17', type=['speak'], text='Ferris wheels are so much fun! I love going on them and spinning round and round.')
        self.graph.add_edge('Node_11', 'Node_17', label='yes')
        self.graph.add_edge('Node_17', 'Node_18', label='Node_17_18')
        self.graph.add_node('Node_18', type=['speak', 'audio'], text='A Ferris wheel is a big wheel that spins round and round. You can find Ferris wheels in carnivals! I love them!', audio='../Assets/audio/laugh.wav')
        self.graph.add_edge('Node_11', 'Node_18', label='no')
        self.graph.add_edge('Node_18', 'Node_19', label='Node_18_19')
        self.graph.add_node('Node_19', type=['speak'], text='Have you ever been on a Ferris wheel? Tell your friends.', pause={'': 10})
        self.graph.add_edge('Node_19', 'Node_20', label='Node_19_20')
        self.graph.add_node('Node_20', type=['speak'], text='Today we`ll build a big Ferris wheel together for our LEGO friends!')
        self.graph.add_edge('Node_20', 'Node_21', label='Node_20_21')
        self.graph.add_node('Node_21', type=['speak', 'face', 'move'], text='Look at the bin at the center of your table! It has all the pieces we need to build a Ferris wheel. So Lets get started!', face=basic_sequences['look_down'], motors='arms_down')
        self.graph.add_edge('Node_21', 'Node_22', label='Node_21_22')
        self.graph.add_node('Node_22', type=['speak'], text='Are you ready?')
        self.graph.add_edge('Node_22', 'Node_23', label='Node_22_23')
        self.graph.add_node('Node_23', type=['hear'], words='["yes", "[unk]"]')
        self.graph.add_node('Node_24', type=['speak', 'show'], text='Can you find the yellow contoller block and four green pins?', image='../Assets/Monolingual_Ferris/ferris_step_01.png')
        self.graph.add_edge('Node_24', 'Node_25', label='Node_24_25')
        self.graph.add_node('Node_25', type=['speak', 'show'], text='When you are done, raise your card.', image='../Assets/Monolingual_Ferris/ferris_step_01.png')
        self.graph.add_edge('Node_25', 'Node_26', label='Node_25_26')
        self.graph.add_node('Node_26', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_27', type=['speak'], text='Still searching? Take your time.')
        self.graph.add_edge('Node_26', 'Node_27', label='no')
        self.graph.add_edge('Node_27', 'Node_26', label='Node_27_26')
        self.graph.add_node('Node_28', type=['speak'], text='Great! That`s our controller!')
        self.graph.add_edge('Node_26', 'Node_28', label='yes')
        self.graph.add_edge('Node_28', 'Node_29', label='Node_28_29')
        self.graph.add_node('Node_29', type=['speak', 'show'], text='Now connect the controller to the gray LEGO plate. the base.', image='../Assets/Monolingual_Ferris/ferris_step_02.png')
        self.graph.add_edge('Node_29', 'Node_30', label='Node_29_30')
        self.graph.add_node('Node_30', type=['speak'], text='One person holds the base while the other clicks the controller in.')
        self.graph.add_edge('Node_30', 'Node_31', label='Node_30_31')
        self.graph.add_node('Node_31', type=['speak', 'show'], text='Raise your card when you are ready.', image='../Assets/Monolingual_Ferris/ferris_step_02.png')
        self.graph.add_edge('Node_31', 'Node_32', label='Node_31_32')
        self.graph.add_node('Node_32', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_33', type=['speak'], text='Not quite done? I will wait.')
        self.graph.add_edge('Node_32', 'Node_33', label='no')
        self.graph.add_edge('Node_33', 'Node_32', label='Node_33_32')
        self.graph.add_node('Node_34', type=['speak'], text='Excellent teamwork!')
        self.graph.add_edge('Node_32', 'Node_34', label='yes')
        self.graph.add_edge('Node_34', 'Node_35', label='Node_34_35')
        self.graph.add_node('Node_35', type=['speak', 'show'], text='This tower is key! First put the yellow part.', image='../Assets/Monolingual_Ferris/ferris_step_03.png')
        self.graph.add_edge('Node_35', 'Node_36', label='Node_35_36')
        self.graph.add_node('Node_36', type=['speak', 'show'], text='Then stack one red brick as base and three bricks, one on top of the other.', image='../Assets/Monolingual_Ferris/ferris_step_05.png')
        self.graph.add_edge('Node_36', 'Node_37', label='Node_36_37')
        self.graph.add_node('Node_37', type=['speka'])
        self.graph.add_edge('Node_37', 'Node_38', label='Node_37_38')
        self.graph.add_node('Node_38', type=['speak', 'show'], text='When it`s done, raise your card.', image='../Assets/Monolingual_Ferris/ferris_step_05.png')
        self.graph.add_edge('Node_38', 'Node_39', label='Node_38_39')
        self.graph.add_node('Node_39', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_40', type=['speak'], text='Not quite done? I will wait.')
        self.graph.add_edge('Node_39', 'Node_40', label='no')
        self.graph.add_edge('Node_40', 'Node_39', label='Node_40_39')
        self.graph.add_node('Node_41', type=['speak'], text='Excellent teamwork!')
        self.graph.add_edge('Node_39', 'Node_41', label='yes')
        self.graph.add_edge('Node_41', 'Node_42', label='Node_41_42')
        self.graph.add_node('Node_42', type=['speak', 'show'], text='Now put the second yellow tower, the yellow plate on top of it and two small orage pieces on top of that. One friend can hold the baseplate while the other presses the tower down.', image='../Assets/Monolingual_Ferris/ferris_step_08.png')
        self.graph.add_edge('Node_42', 'Node_43', label='Node_42_43')
        self.graph.add_node('Node_43', type=['speak', 'show'], text='When it`s steady, raise your card.', image='../Assets/Monolingual_Ferris/ferris_step_08.png')
        self.graph.add_edge('Node_43', 'Node_44', label='Node_43_44')
        self.graph.add_node('Node_44', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_45', type=['speak'], text='Still building? I will wait for your signal.')
        self.graph.add_edge('Node_44', 'Node_45', label='no')
        self.graph.add_edge('Node_45', 'Node_44', label='Node_45_44')
        self.graph.add_node('Node_46', type=['speak'], text='One tower is ready! Great job.')
        self.graph.add_edge('Node_44', 'Node_46', label='yes')
        self.graph.add_edge('Node_46', 'Node_47', label='Node_46_47')
        self.graph.add_node('Node_47', type=['speak', 'show'], text='Find the light piece and connect green pieces to it, similar to the motor.', image='../Assets/Monolingual_Ferris/ferris_step_09.png', pause={'after': 5})
        self.graph.add_edge('Node_47', 'Node_48', label='Node_47_48')
        self.graph.add_node('Node_48', type=['speak'], text='Then attach it to the base. Try switching roles, the one who counted can now be the builder!')
        self.graph.add_edge('Node_48', 'Node_49', label='Node_48_49')
        self.graph.add_node('Node_49', type=['speak', 'show'], text='When the light is attached to the base, hold up your cards.', image='../Assets/Monolingual_Ferris/ferris_step_10.png')
        self.graph.add_edge('Node_49', 'Node_50', label='Node_49_50')
        self.graph.add_node('Node_50', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_51', type=['speak'], text='Take your time. I will wait here until the light piece is attached.')
        self.graph.add_edge('Node_50', 'Node_51', label='no')
        self.graph.add_edge('Node_51', 'Node_50', label='Node_51_50')
        self.graph.add_node('Node_52', type=['speak'], text='Awesome!')
        self.graph.add_edge('Node_50', 'Node_52', label='yes')
        self.graph.add_edge('Node_52', 'Node_53', label='Node_52_53')
        self.graph.add_node('Node_53', type=['speak', 'show'], text='Like the light, find the motor, attach green pins to it.', image='../Assets/Monolingual_Ferris/ferris_step_11.png', pause={'after': 5})
        self.graph.add_edge('Node_53', 'Node_54', label='Node_53_54')
        self.graph.add_node('Node_54', type=['speak'], text='Then attach the motor to the tower.')
        self.graph.add_edge('Node_54', 'Node_55', label='Node_54_55')
        self.graph.add_node('Node_55', type=['speak', 'show'], text='When it is attached, raise your card.', image='../Assets/Monolingual_Ferris/ferris_step_12.png')
        self.graph.add_edge('Node_55', 'Node_56', label='Node_55_56')
        self.graph.add_node('Node_56', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_57', type=['speak'], text='Let me know when it is attached. I will wait!')
        self.graph.add_edge('Node_56', 'Node_57', label='no')
        self.graph.add_edge('Node_57', 'Node_56', label='Node_57_56')
        self.graph.add_node('Node_58', type=['speak'], text='That was great teamwork!')
        self.graph.add_edge('Node_56', 'Node_58', label='yes')
        self.graph.add_edge('Node_58', 'Node_59', label='Node_58_59')
        self.graph.add_node('Node_59', type=['speak'], text='You figures need a way to reach the ferris wheel. How about building stairs?')
        self.graph.add_edge('Node_59', 'Node_60', label='Node_59_60')
        self.graph.add_node('Node_60', type=['speak', 'show'], text='Find and connect the yellow brick and the blue tiles.', image='../Assets/Monolingual_Ferris/ferris_step_13.png', pause={'after': 5})
        self.graph.add_edge('Node_60', 'Node_61', label='Node_60_61')
        self.graph.add_node('Node_61', type=['speak'], text='Then connect two more blue tiles.')
        self.graph.add_edge('Node_61', 'Node_62', label='Node_61_62')
        self.graph.add_node('Node_62', type=['speak', 'show'], text='When they`re all connected, raise your card.', image='../Assets/Monolingual_Ferris/ferris_step_14.png')
        self.graph.add_edge('Node_62', 'Node_63', label='Node_62_63')
        self.graph.add_node('Node_63', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_64', type=['speak'], text='Still snapping them in? I will wait until you are done.')
        self.graph.add_edge('Node_63', 'Node_64', label='no')
        self.graph.add_edge('Node_64', 'Node_63', label='Node_64_63')
        self.graph.add_node('Node_65', type=['speak'], text='You built stairs! What a super team!')
        self.graph.add_edge('Node_63', 'Node_65', label='yes')
        self.graph.add_edge('Node_65', 'Node_66', label='Node_65_66')
        self.graph.add_node('Node_66', type=['speak', 'show'], text='find the rod and put it in the motor. That will make the ferris wheel turn.', image='../Assets/Monolingual_Ferris/ferris_step_15.png', pause={'after': 15})
        self.graph.add_edge('Node_66', 'Node_67', label='Node_66_67')
        self.graph.add_node('Node_67', type=['speak', 'show'], text='Now we build the arms of the ferris wheel. First, start with the main straucture.', image='../Assets/Monolingual_Ferris/ferris_step_16.png', pause={'after': 15})
        self.graph.add_edge('Node_67', 'Node_68', label='Node_67_68')
        self.graph.add_node('Node_68', type=['speak', 'show'], text='Then connect the green pieces to the round wheel center to form an X. Take turns holding the wheel while your partner adds the arms. Then switch.', image='../Assets/Monolingual_Ferris/ferris_step_17.png')
        self.graph.add_edge('Node_68', 'Node_69', label='Node_68_69')
        self.graph.add_node('Node_69', type=['speak', 'show'], text='When they`re all connected, raise your card.', image='../Assets/Monolingual_Ferris/ferris_step_17.png')
        self.graph.add_edge('Node_69', 'Node_70', label='Node_69_70')
        self.graph.add_node('Node_70', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_71', type=['speak'], text='Still snapping them in? I will wait until you are done.')
        self.graph.add_edge('Node_70', 'Node_71', label='no')
        self.graph.add_edge('Node_71', 'Node_70', label='Node_71_70')
        self.graph.add_node('Node_72', type=['speak'], text='You made an X! What a super team!')
        self.graph.add_edge('Node_70', 'Node_72', label='yes')
        self.graph.add_edge('Node_72', 'Node_73', label='Node_72_73')
        self.graph.add_node('Node_73', type=['speak'], text='Now for the final pieces of the wheel.')
        self.graph.add_edge('Node_73', 'Node_74', label='Node_73_74')
        self.graph.add_node('Node_74', type=['speak', 'show'], text='Put one more purple circle.', image='../Assets/Monolingual_Ferris/ferris_step_18.png', pause={'after': 10})
        self.graph.add_edge('Node_74', 'Node_75', label='Node_74_75')
        self.graph.add_node('Node_75', type=['speak', 'show'], text='Then four white pieces. Work together.', image='../Assets/Monolingual_Ferris/ferris_step_19.png', pause={'after': 10})
        self.graph.add_edge('Node_75', 'Node_76', label='Node_75_76')
        self.graph.add_node('Node_76', type=['speak', 'show'], text='Then a green round piece.', image='../Assets/Monolingual_Ferris/ferris_step_20.png', pause={'after': 5})
        self.graph.add_edge('Node_76', 'Node_77', label='Node_76_77')
        self.graph.add_node('Node_77', type=['speak', 'show'], text='And an orange cone.', image='../Assets/Monolingual_Ferris/ferris_step_21.png', pause={'after': 10})
        self.graph.add_edge('Node_77', 'Node_78', label='Node_77_78')
        self.graph.add_node('Node_78', type=['speak'], text='The seats are next. You need to build four seat, one on each arm of the wheel. work together.')
        self.graph.add_edge('Node_78', 'Node_79', label='Node_78_79')
        self.graph.add_node('Node_79', type=['speak', 'show'], text='Let me know when you are done.', image='../Assets/Monolingual_Ferris/ferris_step_22.png')
        self.graph.add_edge('Node_79', 'Node_80', label='Node_79_80')
        self.graph.add_node('Node_80', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_81', type=['speak'], text='Still finalizing those seats? I will wait until you are done.')
        self.graph.add_edge('Node_80', 'Node_81', label='no')
        self.graph.add_edge('Node_81', 'Node_80', label='Node_81_80')
        self.graph.add_node('Node_82', type=['speak'], text='You have the wheel! What a great team!')
        self.graph.add_edge('Node_80', 'Node_82', label='yes')
        self.graph.add_edge('Node_82', 'Node_83', label='Node_82_83')
        self.graph.add_node('Node_83', type=['speak', 'show'], text='Now gently slide the wheel onto the axle. Be very careful!. One of you can hold the axle, while the other pushes the wheel.', image='../Assets/Monolingual_Ferris/ferris_step_23.png', pause={'after': 10})
        self.graph.add_edge('Node_83', 'Node_84', label='Node_83_84')
        self.graph.add_node('Node_84', type=['speak'], text='Now, Lets test it!  If it spins nicely, raise your card.')
        self.graph.add_edge('Node_84', 'Node_85', label='Node_84_85')
        self.graph.add_node('Node_85', type=['find'], what='qr', timeout=60, data=['child number 1', 'child number 2', 'child number 3', 'child number 4'])
        self.graph.add_node('Node_86', type=['speak'], text='Try again and raise your card when the wheel is spinning well.')
        self.graph.add_edge('Node_85', 'Node_86', label='no')
        self.graph.add_edge('Node_86', 'Node_85', label='Node_86_85')
        self.graph.add_node('Node_87', type=['speak', 'move'], text='You did it! Our Ferris Wheel is standing tall and spinning around! You built it together. high five your friend and give a big smile!', motors='Clap your hands!')
        self.graph.add_edge('Node_85', 'Node_87', label='yes')
        self.graph.add_edge('Node_87', 'Node_88', label='Node_87_88')


if __name__ == "__main__":
    sg = Monolingual_Ferris()
    sg.init_graph()

    fuzzy = Character(child=True, gender='female', activity='Monolingual_Ferris', languages=['en'])
    script = Script(graph=sg, character=fuzzy)
    script.generateAllSpeech()
    script.check_assets()

